export const dummyProduct = {
  data: {
    id: "100",
    type: "catalogue",
    attributes: {
      name: "Offer catalogue26",
      brand: null,
      tags: [],
      reviews: [],
      fit_discription_arabic : "jibw",
      prodcut_care_arabic : "jibw",
      sku: null,
      description: "Lorem Ipsum",
      manufacture_date: null,
      length: null,
      breadth: null,
      height: null,
      stock_qty: null,
      availability: null,
      weight: null,
      price: null,
      recommended: null,
      on_sale: null,
      sale_price: null,
      discount: null,
      is_wishlist: false,
      product_number: null,
      primary_image:
        "https://example.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbU1EIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fa8c2ed446d105b83bac260ebb059333aa370c42/front_image.jpg",
      gender: "female",
      brand_name: "Hues",
      material: "Cotton",
      fit: "Slimfit",
      prodcut_care: "Handwash",
      list_the_product: "listed",
      fit_discription: null,
      category: {
        id: "65",
        type: "category",
        attributes: {
          id: 65,
          name: "Women's Clothing",
          status: "active",
          created_at: "2023-12-08T10:31:06.580Z",
          updated_at: "2023-12-14T10:56:24.931Z",
          image:
            "https://example.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0FDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--65f399f30c77e45c14e0b766609fbb5797fdfc56/White.jpg",
        },
      },
      sub_category: {
        id: "435",
        type: "sub_category",
        attributes: {
          id: 435,
          name: "Dresses",
          created_at: "2023-12-08T10:31:06.697Z",
          updated_at: "2023-12-08T10:31:06.697Z",
          image: "",
        },
      },
      sub_sub_category: {
        id: "1",
        type: "sub_sub_category",
        attributes: {
          id: 1,
          name: "Casual Dresses",
          created_at: "2023-12-08T10:31:06.744Z",
          updated_at: "2023-12-08T10:31:06.744Z",
          image: "",
        },
      },
      service: null,
      average_rating: 0,
      catalogue_variants: [
        {
          id: "119",
          type: "catalogue_variant",
          attributes: {
            id: 119,
            catalogue_id: 100,
            catalogue_variant_color_id: 7,
            catalogue_variant_color: {
              id: 7,
              name: "Grey",
              created_at: "2023-10-05T05:19:28.122Z",
              updated_at: "2023-10-05T05:19:28.122Z",
            },
            catalogue_variant_size_id: 1,
            catalogue_variant_size: {
              id: 1,
              name: "Small",
              created_at: "2023-09-22T04:45:35.966Z",
              updated_at: "2023-09-22T04:45:35.966Z",
            },
            price: "1025.0",
            stock_qty: 26,
            on_sale: null,
            sale_price: null,
            discount_price: null,
            length: null,
            breadth: null,
            height: null,
            created_at: "2024-02-01T11:01:12.461Z",
            updated_at: "2024-02-12T10:07:07.627Z",
            low_stock_threshold: 0,
            is_listed: true,
            front_image:
              "https://example.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbU1EIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fa8c2ed446d105b83bac260ebb059333aa370c42/front_image.jpg",
            back_image:
              "https://example.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVFEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--834e1919245d405871fd7d89f408e540f392f901/back_image.jpg",
            side_image: "",
            pair_it_with: [
              {
                id: "121",
                type: "inventory_management",
                attributes: {
                  id: 121,
                  catalogue_id: 102,
                  product_name: "Offer catalogue28",
                  product_description: "Lorem Ipsum",
                  sku: "A28",
                  stock_qty: 28,
                  low_stock_threshold: 0,
                  is_listed: true,
                  price: "1027.0",
                  size: "Small",
                  colour: "Grey",
                  gender: "male",
                  front_image: "",
                },
              },
              {
                id: "120",
                type: "inventory_management",
                attributes: {
                  id: 120,
                  catalogue_id: 101,
                  product_name: "Offer catalogue27",
                  product_description: "Lorem Ipsum",
                  sku: "A27",
                  stock_qty: 3,
                  low_stock_threshold: 0,
                  is_listed: true,
                  price: "1026.0",
                  size: "Small",
                  colour: "Grey",
                  gender: "male",
                  front_image: "",
                },
              },
            ],
          },
        },
      ],
      catalogue_variants_with_store: [
        {
          id: "119",
          type: "catalogue_variant",
          attributes: {
            id: 119,
            catalogue_id: 100,
            catalogue_variant_color_id: 7,
            catalogue_variant_color: {
              id: 7,
              name: "Grey",
              created_at: "2023-10-05T05:19:28.122Z",
              updated_at: "2023-10-05T05:19:28.122Z",
            },
            catalogue_variant_size_id: 1,
            catalogue_variant_size: {
              id: 1,
              name: "Small",
              created_at: "2023-09-22T04:45:35.966Z",
              updated_at: "2023-09-22T04:45:35.966Z",
            },
            price: "1025.0",
            stock_qty: 26,
            on_sale: null,
            sale_price: null,
            discount_price: null,
            length: null,
            breadth: null,
            height: null,
            created_at: "2024-02-01T11:01:12.461Z",
            updated_at: "2024-02-12T10:07:07.627Z",
            low_stock_threshold: 0,
            is_listed: true,
            front_image:
              "https://example.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbU1EIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fa8c2ed446d105b83bac260ebb059333aa370c42/front_image.jpg",
            back_image:
              "https://example.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVFEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--834e1919245d405871fd7d89f408e540f392f901/back_image.jpg",
            side_image: "",
            pair_it_with: [
              {
                id: "121",
                type: "inventory_management",
                attributes: {
                  id: 121,
                  catalogue_id: 102,
                  product_name: "Offer catalogue28",
                  product_description: "Lorem Ipsum",
                  sku: "A28",
                  stock_qty: 28,
                  low_stock_threshold: 0,
                  is_listed: true,
                  price: "1027.0",
                  size: "Small",
                  colour: "Grey",
                  gender: "male",
                  front_image: "",
                },
              },
              {
                id: "120",
                type: "inventory_management",
                attributes: {
                  id: 120,
                  catalogue_id: 101,
                  product_name: "Offer catalogue27",
                  product_description: "Lorem Ipsum",
                  sku: "A27",
                  stock_qty: 3,
                  low_stock_threshold: 0,
                  is_listed: true,
                  price: "1026.0",
                  size: "Small",
                  colour: "Grey",
                  gender: "male",
                  front_image: "",
                },
              },
            ],
          },
          store_info: {
            id: "14",
            type: "bussiness",
            attributes: {
              store_name: "HandM",
              description: null,
              area: "Test Area",
              block: "QA",
              mall_name: null,
              floor: "3",
              unit_number: null,
              city: "Dream City",
              zipcode: "123456",
              driver_instruction: null,
              average_shipping_time: null,
              payment_mode: [],
              store_operating_hours: {},
              status: "Pending",
              latitude: null,
              longitude: null,
              is_open: true,
              available_variants: [
                {
                  id: "119",
                  type: "inventory_management",
                  attributes: {
                    id: 119,
                    catalogue_id: 100,
                    product_name: "Offer catalogue26",
                    product_description: "Lorem Ipsum",
                    sku: "A26",
                    stock_qty: 26,
                    low_stock_threshold: 0,
                    is_listed: true,
                    price: "1025.0",
                    size: "Small",
                    colour: "Grey",
                    gender: "female",
                    front_image:
                      "https://example.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbU1EIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fa8c2ed446d105b83bac260ebb059333aa370c42/front_image.jpg",
                  },
                },
                {
                  id: "127",
                  type: "inventory_management",
                  attributes: {
                    id: 127,
                    catalogue_id: 72,
                    product_name: "Casual Shoes",
                    product_description: "Lorem Ipsum",
                    sku: "Q5",
                    stock_qty: 50,
                    low_stock_threshold: 0,
                    is_listed: true,
                    price: "8900.0",
                    size: "Small",
                    colour: "Grey",
                    gender: "female",
                    front_image: "",
                  },
                },
                {
                  id: "96",
                  type: "inventory_management",
                  attributes: {
                    id: 96,
                    catalogue_id: 78,
                    product_name: "Offer catalogue3",
                    product_description: "Lorem Ipsum",
                    sku: "A3",
                    stock_qty: 3,
                    low_stock_threshold: 0,
                    is_listed: true,
                    price: "1002.0",
                    size: "Small",
                    colour: "Grey",
                    gender: "male",
                    front_image: "",
                  },
                },
                {
                  id: "97",
                  type: "inventory_management",
                  attributes: {
                    id: 97,
                    catalogue_id: 79,
                    product_name: "Offer catalogue4",
                    product_description: "Lorem Ipsum",
                    sku: "A4",
                    stock_qty: 4,
                    low_stock_threshold: 0,
                    is_listed: true,
                    price: "1003.0",
                    size: "Small",
                    colour: "Grey",
                    gender: "male",
                    front_image: "",
                  },
                },
              ],
              image: null,
              email: "tvsseller@yopmail.com",
              contact_number: {
                country_code: "+91",
                phone_number: "9876543210",
              },
              expected_delivery_time: "2024-02-21T14:52:49.764Z",
            },
          },
        },
      ],
      owner_first_name: "fashion",
      owner_last_name: "fashion",
      owner_full_name: "fashion fashion",
      owner_address: null
    },
  },
};

export const dummyProductWithAddress = {
  data: {
    id: "100",
    type: "catalogue",
    attributes: {
      name: "Offer catalogue26",
      brand: null,
      tags: [],
      reviews: [],
      sku: null,
      description: "Lorem Ipsum",
      manufacture_date: null,
      length: null,
      breadth: null,
      height: null,
      stock_qty: null,
      availability: null,
      weight: null,
      price: null,
      recommended: null,
      on_sale: null,
      sale_price: null,
      discount: null,
      is_wishlist: false,
      product_number: null,
      primary_image:
        "https://example.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbU1EIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fa8c2ed446d105b83bac260ebb059333aa370c42/front_image.jpg",
      gender: "female",
      brand_name: "Hues",
      material: "Cotton",
      fit: "Slimfit",
      prodcut_care: "Handwash",
      list_the_product: "listed",
      fit_discription: null,
      category: {
        id: "65",
        type: "category",
        attributes: {
          id: 65,
          name: "Women's Clothing",
          status: "active",
          created_at: "2023-12-08T10:31:06.580Z",
          updated_at: "2023-12-14T10:56:24.931Z",
          image:
            "https://example.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0FDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--65f399f30c77e45c14e0b766609fbb5797fdfc56/White.jpg",
        },
      },
      sub_category: {
        id: "435",
        type: "sub_category",
        attributes: {
          id: 435,
          name: "Dresses",
          created_at: "2023-12-08T10:31:06.697Z",
          updated_at: "2023-12-08T10:31:06.697Z",
          image: "",
        },
      },
      sub_sub_category: {
        id: "1",
        type: "sub_sub_category",
        attributes: {
          id: 1,
          name: "Casual Dresses",
          created_at: "2023-12-08T10:31:06.744Z",
          updated_at: "2023-12-08T10:31:06.744Z",
          image: "",
        },
      },
      service: null,
      average_rating: 0,
      catalogue_variants: [
        {
          id: "119",
          type: "catalogue_variant",
          attributes: {
            id: 119,
            catalogue_id: 100,
            catalogue_variant_color_id: 7,
            catalogue_variant_color: {
              id: 7,
              name: "Grey",
              created_at: "2023-10-05T05:19:28.122Z",
              updated_at: "2023-10-05T05:19:28.122Z",
            },
            catalogue_variant_size_id: 1,
            catalogue_variant_size: {
              id: 1,
              name: "Small",
              created_at: "2023-09-22T04:45:35.966Z",
              updated_at: "2023-09-22T04:45:35.966Z",
            },
            price: "1025.0",
            stock_qty: 26,
            on_sale: null,
            sale_price: null,
            discount_price: null,
            length: null,
            breadth: null,
            height: null,
            created_at: "2024-02-01T11:01:12.461Z",
            updated_at: "2024-02-12T10:07:07.627Z",
            low_stock_threshold: 0,
            is_listed: true,
            front_image:
              "https://example.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbU1EIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fa8c2ed446d105b83bac260ebb059333aa370c42/front_image.jpg",
            back_image:
              "https://example.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVFEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--834e1919245d405871fd7d89f408e540f392f901/back_image.jpg",
            side_image: "",
            pair_it_with: [
              {
                id: "121",
                type: "inventory_management",
                attributes: {
                  id: 121,
                  catalogue_id: 102,
                  product_name: "Offer catalogue28",
                  product_description: "Lorem Ipsum",
                  sku: "A28",
                  stock_qty: 28,
                  low_stock_threshold: 0,
                  is_listed: true,
                  price: "1027.0",
                  size: "Small",
                  colour: "Grey",
                  gender: "male",
                  front_image: "",
                },
              },
              {
                id: "120",
                type: "inventory_management",
                attributes: {
                  id: 120,
                  catalogue_id: 101,
                  product_name: "Offer catalogue27",
                  product_description: "Lorem Ipsum",
                  sku: "A27",
                  stock_qty: 3,
                  low_stock_threshold: 0,
                  is_listed: true,
                  price: "1026.0",
                  size: "Small",
                  colour: "Grey",
                  gender: "male",
                  front_image: "",
                },
              },
            ],
          },
        },
      ],
      catalogue_variants_with_store: [
        {
          id: "119",
          type: "catalogue_variant",
          attributes: {
            id: 119,
            catalogue_id: 100,
            catalogue_variant_color_id: 7,
            catalogue_variant_color: {
              id: 7,
              name: "Grey",
              created_at: "2023-10-05T05:19:28.122Z",
              updated_at: "2023-10-05T05:19:28.122Z",
            },
            catalogue_variant_size_id: 1,
            catalogue_variant_size: {
              id: 1,
              name: "Small",
              created_at: "2023-09-22T04:45:35.966Z",
              updated_at: "2023-09-22T04:45:35.966Z",
            },
            price: "1025.0",
            stock_qty: 26,
            on_sale: null,
            sale_price: null,
            discount_price: null,
            length: null,
            breadth: null,
            height: null,
            created_at: "2024-02-01T11:01:12.461Z",
            updated_at: "2024-02-12T10:07:07.627Z",
            low_stock_threshold: 0,
            is_listed: true,
            front_image:
              "https://example.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbU1EIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fa8c2ed446d105b83bac260ebb059333aa370c42/front_image.jpg",
            back_image:
              "https://example.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVFEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--834e1919245d405871fd7d89f408e540f392f901/back_image.jpg",
            side_image: "",
            pair_it_with: [
              {
                id: "121",
                type: "inventory_management",
                attributes: {
                  id: 121,
                  catalogue_id: 102,
                  product_name: "Offer catalogue28",
                  product_description: "Lorem Ipsum",
                  sku: "A28",
                  stock_qty: 28,
                  low_stock_threshold: 0,
                  is_listed: true,
                  price: "1027.0",
                  size: "Small",
                  colour: "Grey",
                  gender: "male",
                  front_image: "",
                },
              },
              {
                id: "120",
                type: "inventory_management",
                attributes: {
                  id: 120,
                  catalogue_id: 101,
                  product_name: "Offer catalogue27",
                  product_description: "Lorem Ipsum",
                  sku: "A27",
                  stock_qty: 3,
                  low_stock_threshold: 0,
                  is_listed: true,
                  price: "1026.0",
                  size: "Small",
                  colour: "Grey",
                  gender: "male",
                  front_image: "",
                },
              },
            ],
          },
          store_info: {
            id: "14",
            type: "bussiness",
            attributes: {
              store_name: "HandM",
              description: null,
              area: "Test Area",
              block: "QA",
              mall_name: null,
              floor: "3",
              unit_number: null,
              city: "Dream City",
              zipcode: "123456",
              driver_instruction: null,
              average_shipping_time: null,
              payment_mode: [],
              store_operating_hours: {},
              status: "Pending",
              latitude: null,
              longitude: null,
              is_open: true,
              available_variants: [
                {
                  id: "119",
                  type: "inventory_management",
                  attributes: {
                    id: 119,
                    catalogue_id: 100,
                    product_name: "Offer catalogue26",
                    product_description: "Lorem Ipsum",
                    sku: "A26",
                    stock_qty: 26,
                    low_stock_threshold: 0,
                    is_listed: true,
                    price: "1025.0",
                    size: "Small",
                    colour: "Grey",
                    gender: "female",
                    front_image:
                      "https://example.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbU1EIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fa8c2ed446d105b83bac260ebb059333aa370c42/front_image.jpg",
                  },
                },
                {
                  id: "127",
                  type: "inventory_management",
                  attributes: {
                    id: 127,
                    catalogue_id: 72,
                    product_name: "Casual Shoes",
                    product_description: "Lorem Ipsum",
                    sku: "Q5",
                    stock_qty: 50,
                    low_stock_threshold: 0,
                    is_listed: true,
                    price: "8900.0",
                    size: "Small",
                    colour: "Grey",
                    gender: "female",
                    front_image: "",
                  },
                },
                {
                  id: "96",
                  type: "inventory_management",
                  attributes: {
                    id: 96,
                    catalogue_id: 78,
                    product_name: "Offer catalogue3",
                    product_description: "Lorem Ipsum",
                    sku: "A3",
                    stock_qty: 3,
                    low_stock_threshold: 0,
                    is_listed: true,
                    price: "1002.0",
                    size: "Small",
                    colour: "Grey",
                    gender: "male",
                    front_image: "",
                  },
                },
                {
                  id: "97",
                  type: "inventory_management",
                  attributes: {
                    id: 97,
                    catalogue_id: 79,
                    product_name: "Offer catalogue4",
                    product_description: "Lorem Ipsum",
                    sku: "A4",
                    stock_qty: 4,
                    low_stock_threshold: 0,
                    is_listed: true,
                    price: "1003.0",
                    size: "Small",
                    colour: "Grey",
                    gender: "male",
                    front_image: "",
                  },
                },
              ],
              image: null,
              email: "tvsseller@yopmail.com",
              contact_number: {
                country_code: "+91",
                phone_number: "9876543210",
              },
              expected_delivery_time: "2024-02-21T14:52:49.764Z",
            },
          },
        },
      ],
      owner_first_name: "fashion",
      owner_last_name: "fashion",
      owner_full_name: "fashion fashion",
      owner_address: {
          "address": "kn",
          "area": 'aw',
          "block": "test",
          "mall_name": "test",
          "floor": "test",
          "unit_number": 124,
          "city": "indore",
          "zipcode": "452001"
      },
      primary_discounted_percentage:'0'
    },
  },
};

export const addToCartSuccess = {
  data: {
    coupon_message: null,
    order: {
      data: {
        id: "76",
        type: "order",
        attributes: {
          id: 76,
          order_number: "OD00000063",
          title: "Order Summary",
          amount: null,
          order_item_count: 1,
          account_id: 423,
          coupon_code_id: null,
          delivery_address_id: null,
          sub_total: "1025.0",
          total: "1209.5",
          status: "created",
          custom_label: null,
          applied_discount: "0.0",
          cancellation_reason: null,
          order_date: null,
          is_gift: false,
          placed_at: null,
          confirmed_at: null,
          in_transit_at: null,
          delivered_at: null,
          cancelled_at: null,
          refunded_at: null,
          source: null,
          shipment_id: null,
          delivery_charges: null,
          tracking_url: null,
          schedule_time: null,
          payment_failed_at: null,
          payment_pending_at: null,
          returned_at: null,
          tax_charges: "0.0",
          deliver_by: null,
          tracking_number: null,
          is_error: false,
          delivery_error_message: null,
          order_status_id: 1,
          is_group: true,
          is_availability_checked: false,
          shipping_charge: "50.0",
          shipping_discount: "50.0",
          shipping_net_amt: "0.0",
          shipping_total: "0.0",
          total_tax: 184.5,
          created_at: "2024-02-20T04:01:18.579Z",
          updated_at: "2024-02-20T04:01:18.712Z",
          order_deliver_date: null,
          order_deliver_time: null,
          delivery_addresses: [],
          order_return_date: null,
          order_return_time: null,
          razorpay_order_id: null,
          charged: null,
          invoice_id: null,
          invoiced: null,
          order_items: [
            {
              id: "117",
              type: "order_item",
              attributes: {
                id: 117,
                order_management_order_id: 76,
                variant_availability: "available",
                quantity: 1,
                unit_price: "1025.0",
                total_price: "1025.0",
                old_unit_price: null,
                status: "in_cart",
                catalogue_id: 100,
                catalogue_variant_id: 119,
                order_status_id: 1,
                placed_at: null,
                confirmed_at: null,
                in_transit_at: null,
                delivered_at: null,
                cancelled_at: null,
                refunded_at: null,
                manage_placed_status: false,
                manage_cancelled_status: false,
                created_at: "2024-02-20T04:01:18.687Z",
                updated_at: "2024-02-20T04:01:18.710Z",
                reason_of_rejection: null,
                rejected_at: null,
                estimated_delivery_time: "2024-02-22T04:01:18.804Z",
                order_statuses: {
                  order_number: "OD00000063",
                  placed_at: null,
                  confirmed_at: null,
                  in_transit_at: null,
                  delivered_at: null,
                  cancelled_at: null,
                  refunded_at: null,
                },
                catalogue: {
                  id: "100",
                  type: "catalogue",
                  attributes: {
                    name: "Offer catalogue26",
                    brand: null,
                    tags: [],
                    reviews: [],
                    sku: null,
                    description: "Lorem Ipsum",
                    manufacture_date: null,
                    length: null,
                    breadth: null,
                    height: null,
                    stock_qty: null,
                    availability: null,
                    weight: null,
                    price: null,
                    recommended: null,
                    on_sale: null,
                    sale_price: null,
                    discount: null,
                    is_wishlist: false,
                    product_number: null,
                    primary_image:
                      "https://example.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbU1EIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fa8c2ed446d105b83bac260ebb059333aa370c42/front_image.jpg",
                    gender: "female",
                    brand_name: "Hues",
                    material: "Cotton",
                    fit: "Slimfit",
                    prodcut_care: "Handwash",
                    list_the_product: "listed",
                    fit_discription: null,
                    category: {
                      id: "65",
                      type: "category",
                      attributes: {
                        id: 65,
                        name: "Women's Clothing",
                        status: "active",
                        created_at: "2023-12-08T10:31:06.580Z",
                        updated_at: "2023-12-14T10:56:24.931Z",
                        image:
                          "https://example.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0FDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--65f399f30c77e45c14e0b766609fbb5797fdfc56/White.jpg",
                      },
                    },
                    sub_category: {
                      id: "435",
                      type: "sub_category",
                      attributes: {
                        id: 435,
                        name: "Dresses",
                        created_at: "2023-12-08T10:31:06.697Z",
                        updated_at: "2023-12-08T10:31:06.697Z",
                        image: "",
                      },
                    },
                    sub_sub_category: {
                      id: "1",
                      type: "sub_sub_category",
                      attributes: {
                        id: 1,
                        name: "Casual Dresses",
                        created_at: "2023-12-08T10:31:06.744Z",
                        updated_at: "2023-12-08T10:31:06.744Z",
                        image: "",
                      },
                    },
                    service: null,
                    average_rating: 0,
                    catalogue_variants: [
                      {
                        id: "119",
                        type: "catalogue_variant",
                        attributes: {
                          id: 119,
                          catalogue_id: 100,
                          catalogue_variant_color_id: 7,
                          catalogue_variant_color: {
                            id: 7,
                            name: "Grey",
                            created_at: "2023-10-05T05:19:28.122Z",
                            updated_at: "2023-10-05T05:19:28.122Z",
                          },
                          catalogue_variant_size_id: 1,
                          catalogue_variant_size: {
                            id: 1,
                            name: "Small",
                            created_at: "2023-09-22T04:45:35.966Z",
                            updated_at: "2023-09-22T04:45:35.966Z",
                          },
                          price: "1025.0",
                          stock_qty: 26,
                          on_sale: null,
                          sale_price: null,
                          discount_price: null,
                          length: null,
                          breadth: null,
                          height: null,
                          created_at: "2024-02-01T11:01:12.461Z",
                          updated_at: "2024-02-12T10:07:07.627Z",
                          low_stock_threshold: 0,
                          is_listed: true,
                          front_image:
                            "https://example.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbU1EIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fa8c2ed446d105b83bac260ebb059333aa370c42/front_image.jpg",
                          back_image:
                            "https://example.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVFEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--834e1919245d405871fd7d89f408e540f392f901/back_image.jpg",
                          side_image: "",
                          pair_it_with: [
                            {
                              id: "121",
                              type: "inventory_management",
                              attributes: {
                                id: 121,
                                catalogue_id: 102,
                                product_name: "Offer catalogue28",
                                product_description: "Lorem Ipsum",
                                sku: "A28",
                                stock_qty: 28,
                                low_stock_threshold: 0,
                                is_listed: true,
                                price: "1027.0",
                                size: "Small",
                                colour: "Grey",
                                gender: "male",
                                front_image: "",
                                brand_name: "Hues",
                              },
                            },
                            {
                              id: "120",
                              type: "inventory_management",
                              attributes: {
                                id: 120,
                                catalogue_id: 101,
                                product_name: "Offer catalogue27",
                                product_description: "Lorem Ipsum",
                                sku: "A27",
                                stock_qty: 3,
                                low_stock_threshold: 0,
                                is_listed: true,
                                price: "1026.0",
                                size: "Small",
                                colour: "Grey",
                                gender: "male",
                                front_image: "",
                                brand_name: "Hues",
                              },
                            },
                          ],
                        },
                      },
                    ],
                    catalogue_variants_with_store: [
                      {
                        id: "119",
                        type: "catalogue_variant",
                        attributes: {
                          id: 119,
                          catalogue_id: 100,
                          catalogue_variant_color_id: 7,
                          catalogue_variant_color: {
                            id: 7,
                            name: "Grey",
                            created_at: "2023-10-05T05:19:28.122Z",
                            updated_at: "2023-10-05T05:19:28.122Z",
                          },
                          catalogue_variant_size_id: 1,
                          catalogue_variant_size: {
                            id: 1,
                            name: "Small",
                            created_at: "2023-09-22T04:45:35.966Z",
                            updated_at: "2023-09-22T04:45:35.966Z",
                          },
                          price: "1025.0",
                          stock_qty: 26,
                          on_sale: null,
                          sale_price: null,
                          discount_price: null,
                          length: null,
                          breadth: null,
                          height: null,
                          created_at: "2024-02-01T11:01:12.461Z",
                          updated_at: "2024-02-12T10:07:07.627Z",
                          low_stock_threshold: 0,
                          is_listed: true,
                          front_image:
                            "https://example.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbU1EIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fa8c2ed446d105b83bac260ebb059333aa370c42/front_image.jpg",
                          back_image:
                            "https://example.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVFEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--834e1919245d405871fd7d89f408e540f392f901/back_image.jpg",
                          side_image: "",
                          pair_it_with: [
                            {
                              id: "121",
                              type: "inventory_management",
                              attributes: {
                                id: 121,
                                catalogue_id: 102,
                                product_name: "Offer catalogue28",
                                product_description: "Lorem Ipsum",
                                sku: "A28",
                                stock_qty: 28,
                                low_stock_threshold: 0,
                                is_listed: true,
                                price: "1027.0",
                                size: "Small",
                                colour: "Grey",
                                gender: "male",
                                front_image: "",
                                brand_name: "Hues",
                              },
                            },
                            {
                              id: "120",
                              type: "inventory_management",
                              attributes: {
                                id: 120,
                                catalogue_id: 101,
                                product_name: "Offer catalogue27",
                                product_description: "Lorem Ipsum",
                                sku: "A27",
                                stock_qty: 3,
                                low_stock_threshold: 0,
                                is_listed: true,
                                price: "1026.0",
                                size: "Small",
                                colour: "Grey",
                                gender: "male",
                                front_image: "",
                                brand_name: "Hues",
                              },
                            },
                          ],
                        },
                        store_info: {
                          id: "14",
                          type: "bussiness",
                          attributes: {
                            store_name: "HandM",
                            description: null,
                            area: "Test Area",
                            block: "QA",
                            mall_name: null,
                            floor: "3",
                            unit_number: null,
                            city: "Dream City",
                            zipcode: "123456",
                            driver_instruction: null,
                            average_shipping_time: null,
                            payment_mode: [],
                            store_operating_hours: {},
                            status: "Pending",
                            latitude: null,
                            longitude: null,
                            is_open: true,
                            available_variants: [
                              {
                                id: "119",
                                type: "inventory_management",
                                attributes: {
                                  id: 119,
                                  catalogue_id: 100,
                                  product_name: "Offer catalogue26",
                                  product_description: "Lorem Ipsum",
                                  sku: "A26",
                                  stock_qty: 26,
                                  low_stock_threshold: 0,
                                  is_listed: true,
                                  price: "1025.0",
                                  size: "Small",
                                  colour: "Grey",
                                  gender: "female",
                                  front_image:
                                    "https://example.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbU1EIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fa8c2ed446d105b83bac260ebb059333aa370c42/front_image.jpg",
                                  brand_name: "Hues",
                                },
                              },
                              {
                                id: "127",
                                type: "inventory_management",
                                attributes: {
                                  id: 127,
                                  catalogue_id: 72,
                                  product_name: "Casual Shoes",
                                  product_description: "Lorem Ipsum",
                                  sku: "Q5",
                                  stock_qty: 50,
                                  low_stock_threshold: 0,
                                  is_listed: true,
                                  price: "8900.0",
                                  size: "Small",
                                  colour: "Grey",
                                  gender: "female",
                                  front_image: "",
                                  brand_name: "H&M",
                                },
                              },
                              {
                                id: "96",
                                type: "inventory_management",
                                attributes: {
                                  id: 96,
                                  catalogue_id: 78,
                                  product_name: "Offer catalogue3",
                                  product_description: "Lorem Ipsum",
                                  sku: "A3",
                                  stock_qty: 3,
                                  low_stock_threshold: 0,
                                  is_listed: true,
                                  price: "1002.0",
                                  size: "Small",
                                  colour: "Grey",
                                  gender: "male",
                                  front_image: "",
                                  brand_name: "Hues",
                                },
                              },
                              {
                                id: "97",
                                type: "inventory_management",
                                attributes: {
                                  id: 97,
                                  catalogue_id: 79,
                                  product_name: "Offer catalogue4",
                                  product_description: "Lorem Ipsum",
                                  sku: "A4",
                                  stock_qty: 4,
                                  low_stock_threshold: 0,
                                  is_listed: true,
                                  price: "1003.0",
                                  size: "Small",
                                  colour: "Grey",
                                  gender: "male",
                                  front_image: "",
                                  brand_name: "Hues",
                                },
                              },
                            ],
                            image: null,
                            email: "tvsseller@yopmail.com",
                            contact_number: {
                              country_code: "+91",
                              phone_number: "9876543210",
                            },
                            expected_delivery_time: "2024-02-22T04:01:19.154Z",
                          },
                        },
                      },
                    ],
                  },
                },
                catalogue_variant: {
                  id: "119",
                  type: "catalogue_variant",
                  attributes: {
                    id: 119,
                    catalogue_id: 100,
                    catalogue_variant_color_id: 7,
                    catalogue_variant_color: {
                      id: 7,
                      name: "Grey",
                      created_at: "2023-10-05T05:19:28.122Z",
                      updated_at: "2023-10-05T05:19:28.122Z",
                    },
                    catalogue_variant_size_id: 1,
                    catalogue_variant_size: {
                      id: 1,
                      name: "Small",
                      created_at: "2023-09-22T04:45:35.966Z",
                      updated_at: "2023-09-22T04:45:35.966Z",
                    },
                    price: "1025.0",
                    stock_qty: 26,
                    on_sale: null,
                    sale_price: null,
                    discount_price: null,
                    length: null,
                    breadth: null,
                    height: null,
                    created_at: "2024-02-01T11:01:12.461Z",
                    updated_at: "2024-02-12T10:07:07.627Z",
                    low_stock_threshold: 0,
                    is_listed: true,
                    front_image:
                      "https://example.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbU1EIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fa8c2ed446d105b83bac260ebb059333aa370c42/front_image.jpg",
                    back_image:
                      "https://example.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVFEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--834e1919245d405871fd7d89f408e540f392f901/back_image.jpg",
                    side_image: "",
                    pair_it_with: [
                      {
                        id: "121",
                        type: "inventory_management",
                        attributes: {
                          id: 121,
                          catalogue_id: 102,
                          product_name: "Offer catalogue28",
                          product_description: "Lorem Ipsum",
                          sku: "A28",
                          stock_qty: 28,
                          low_stock_threshold: 0,
                          is_listed: true,
                          price: "1027.0",
                          size: "Small",
                          colour: "Grey",
                          gender: "male",
                          front_image: "",
                          brand_name: "Hues",
                        },
                      },
                      {
                        id: "120",
                        type: "inventory_management",
                        attributes: {
                          id: 120,
                          catalogue_id: 101,
                          product_name: "Offer catalogue27",
                          product_description: "Lorem Ipsum",
                          sku: "A27",
                          stock_qty: 3,
                          low_stock_threshold: 0,
                          is_listed: true,
                          price: "1026.0",
                          size: "Small",
                          colour: "Grey",
                          gender: "male",
                          front_image: "",
                          brand_name: "Hues",
                        },
                      },
                    ],
                  },
                  store_info: null,
                },
              },
            },
          ],
        },
      },
    },
  },
};

export const shareData = {
  "RestAPIResponceDataMessage": "63ecc33e-e48e-41be-bf2f-039d0e383c7b",
  "RestAPIResponceSuccessMessage": {
      "data": {
          "attributes": [],
          "id": "282",
          "type": "catalogue"
      },
      "shareable_link": "https://fashionaggregator-326157-ruby.b326157.dev.eastus.az.svc.builder.cafe/bx_block_catalogue/share_catalogue_descriptions/282?token=eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MTA4MiwiZXhwIjoxNzMwNTM1MzYyLCJ0b2tlbl90eXBlIjoibG9naW4ifQ.mti5_5shj7X4x04GmGuCLxC5AUZV_1WTqe8LPcuUsQ8NbbLKAALJdL9av51X1LtnQvmw0dn1286oo05ZFkgl1w"
  }
}