export const circleIcon = require("../assets/circle.png");
export const crossIcon = require("../assets/cross.png");
export const backIcon = require("../assets/backIcon.png");
export const rightArrow = require("../assets/rightArrow.png")
export const blackRightIcon = require("../assets/blackRightIcon.png")
export const calender = require("../assets/calender.png")
export const eyeIcon =require("../assets/I_Icon.png")
export const check = require("../assets/check.png");
export const optionButton= require("../assets/optionButton.png");