export const dummyCountryList = [
  {
    numeric_code: "+992",
    country_full_name: "Tajikistan",
    country_code: "TJ",
    country_flag: "🇹🇯",
  },
  {
    numeric_code: "+1",
    country_full_name: "Jamaica",
    country_code: "JM",
    country_flag: "🇯🇲",
  },
  {
    numeric_code: "+509",
    country_full_name: "Haiti",
    country_code: "HT",
    country_flag: "🇭🇹",
  },
  {
    numeric_code: "+965",
    country_full_name: "Kuwait",
    country_code: "KW",
    country_flag: "🇰🇼",
  },
];

export const customProfileResponse = {
  data: {
    id: "11",
    type: "stylist_account",
    attributes: {
      status: 0,
      preferred_language: "english",
      location_info: "Random",
      address: "",
      contact_details: null,
      instagram: "",
      facebook: "",
      tiktok: "",
      pinterest: "",
      biography: "hu",
      year_of_experience: "2",
      expertise: "sdfads",
      block: "Blk",
      mall_name: "",
      floor: "",
      unit_number: null,
      city: "",
      zipcode: "",
      contact_number: "",
      google_pay: null,
      apple_pay: null,
      account_id: 780,
      passport_status: null,
      moa_status: null,
      authorized_signature_status: null,
      commercial_license_status: null,
      business_bank_account_status: null,
      bank_detail: {
        data: [
          {
            id: "65",
            type: "bank_detail",
            attributes: {
              bank_name: null,
              account_holder_name: "ARNAB",
              bank_code: null,
              account_number: "332960",
              iban: "DE187E422",
              is_default: false,
            },
          },
        ],
      },
      passport: null,
      authorized_signature: null,
      commercial_license: null,
      moa: null,
      business_bank_account: null,
      profile_picture:
        "https://example.com/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdHdJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d44abd99068a3dedf3ca1c7c4e6bb0a85efe04a1/profile_photo.jpeg",
    },
  },
};

export const sourceProductResponse = {
  data: [
    {
      id: "12",
      type: "product_sourcing_request",
      attributes: {
        id: 12,
        product_name: "test",
        request_status: "pending",
        max_price: "50.0",
        min_price: "10.0",
        sizes: ["large"],
        description: "testing",
        gender: "female",
        quantity: 1,
        colours: ["red"],
        images: [
          {
            id: 2647,
            url: null,
          },
        ],
        total_stylist_offer_requests: 0,
        product_sourcing_stylist_prices: [],
      },
    },
    {
      id: "13",
      type: "product_sourcing_request",
      attributes: {
        id: 13,
        product_name: "test",
        request_status: "pending",
        max_price: "123.0",
        min_price: "12.0",
        sizes: ["L", "M"],
        description: "oijdiohiosji",
        gender: "male",
        quantity: 2,
        colours: ["red", "black"],
        images: [
          {
            id: 2821,
            url: "NA",
          },
        ],
        total_stylist_offer_requests: 0,
        product_sourcing_stylist_prices: [],
      },
    },
  ],
};

export const sourceProductResponse6Data = {
  data: {
    id: "29",
    type: "sourcing_request",
    attributes: {
      id: 29,
      product_name: "Hsjssj",
      request_status: "pending",
      max_price: "600.0",
      min_price: "100.0",
      sizes: ["Xl"],
      description: "Bsjss",
      gender: "female",
      quantity: 300,
      colours: ["Red"],
      images: [
        {
          id: 3532,
          url: "profile.jpg",
        },
      ],
      product_sourcing_stylist_prices: [
        {
          id: 13,
          request_id: 29,
          account_id: 972,
          quote_price: 300.0,
          product_description: "uiosdiouiow eyio eiofy e8o fl ",
          request_status: "waiting",
          created_at: "2024-07-22T10:51:22.440Z",
          updated_at: "2024-07-22T10:51:22.448Z",
          full_name: "fashion fashion",
          images: [
            {
              id: 3815,
              url: "image.jpg",
            },
          ],
        },
      ],
    },
  },
};

export const buyerProductSourcingViewData = {
  data: {
    id: "36",
    type: "product_sourcing_request",
    attributes: {
      id: 36,
      product_name: "Khel",
      request_status: "pending",
      max_price: "600.0",
      min_price: "250.0",
      sizes: ["Large"],
      description:
        "Uske ghumi Jan of the 3D or 5th se hu um Or hm ex of ring de in hu de for FB 3D nu",
      gender: "female",
      quantity: 600,
      colours: ["Yellow"],
      images: [
        {
          id: 3712,
          url: "profile.jpg",
        },
      ],
      total_stylist_offer_requests: 1,
      product_sourcing_stylist_prices: [
        {
          id: 11,
          request_id: 36,
          account_id: 972,
          quote_price: 60.0,
          product_description: "Will be created ",
          request_status: "waiting",
          created_at: "2024-07-18T11:25:46.158Z",
          updated_at: "2024-07-18T11:25:46.198Z",
          full_name: "fashion fashion",
          images: [
            {
              id: 3737,
              url: "view_.png",
            },
          ],
        },
        {
          id: 12,
          request_id: 36,
          account_id: 971,
          quote_price: 50.0,
          product_description: "Will be created ",
          request_status: "accepted",
          created_at: "2024-07-18T11:25:46.158Z",
          updated_at: "2024-07-18T11:25:46.198Z",
          full_name: "fashion fashion",
          images: [
            {
              id: 3737,
              url: "view_.png",
            },
          ],
        },
        {
          id: 13,
          request_id: 36,
          account_id: 941,
          quote_price: 50.0,
          product_description: "Will be created ",
          request_status: "rejected",
          created_at: "2024-07-18T11:25:46.158Z",
          updated_at: "2024-07-18T11:25:46.198Z",
          full_name: "fashion fashion",
          images: [
            {
              id: 3737,
              url: "view_.png",
            },
          ],
        },
      ],
    },
  },
};

export const sourceProductResponse7Data = {
  data: {
    id: "29",
    type: "sourcing_request",
    attributes: {
      id: 29,
      product_name: "Hsjssj",
      request_status: "pending",
      max_price: "600.0",
      min_price: "100.0",
      sizes: ["Xl"],
      description: "Bsjss",
      gender: "female",
      quantity: 300,
      colours: ["Red"],
      images: [
        {
          id: 3532,
          url: "profile.jpg",
        },
      ],
      product_sourcing_stylist_prices: [],
    },
  },
};

export const stylistArr = [
  {
    id: "188",
    type: "stylist",
    attributes: {
      activated: true,
      country_code: null,
      email: "stylist@yopmail.com",
      first_name: null,
      full_phone_number: "",
      last_name: null,
      full_name: "Stylist",
      phone_number: null,
      type: "SocialAccount",
      created_at: "2023-11-01T06:58:13.713Z",
      updated_at: "2023-11-01T06:58:13.713Z",
      device_id: null,
      unique_auth_id: "12345765",
      driver_status: "offline",
      seller_status: "Signup",
      approve_status: "Pending",
      language: "English",
      currency: "Dollar",
      bio: null,
      profile_picture: null,
      is_favorite: false,
    },
  },
  {
    id: "79",
    type: "stylist",
    attributes: {
      activated: true,
      country_code: "91",
      email: "stylist1@yopmail.com",
      first_name: null,
      full_phone_number: "919998055446",
      last_name: null,
      full_name: "stylist1",
      phone_number: "9998055446",
      type: "SocialAccount",
      created_at: "2023-10-04T09:21:40.777Z",
      updated_at: "2024-02-08T10:14:39.977Z",
      device_id: null,
      unique_auth_id: "12345765",
      driver_status: "offline",
      seller_status: "Signup",
      approve_status: "Pending",
      language: "English",
      currency: "Dollar",
      bio: "nn",
      profile_picture: null,
      is_favorite: true,
    },
  },
  {
    id: "80",
    type: "stylist",
    attributes: {
      activated: true,
      country_code: null,
      email: "chandni1@gmail.com",
      first_name: null,
      full_phone_number: "",
      last_name: null,
      full_name: "chandni",
      phone_number: null,
      type: "SocialAccount",
      created_at: "2023-10-04T09:58:36.026Z",
      updated_at: "2023-10-04T10:59:00.920Z",
      device_id: null,
      unique_auth_id: "12345765",
      driver_status: "offline",
      seller_status: "Signup",
      approve_status: "Pending",
      language: "English",
      currency: "Dollar",
      bio: null,
      profile_picture: null,
      is_favorite: false,
    },
  },
  {
    id: "83",
    type: "stylist",
    attributes: {
      activated: true,
      country_code: null,
      email: "stylist041a0@yopmail.com",
      first_name: null,
      full_phone_number: "",
      last_name: null,
      full_name: "stylist",
      phone_number: null,
      type: "SocialAccount",
      created_at: "2023-10-04T12:08:04.414Z",
      updated_at: "2023-10-04T12:08:04.414Z",
      device_id: null,
      unique_auth_id: "12345445",
      driver_status: "offline",
      seller_status: "Signup",
      approve_status: "Pending",
      language: "English",
      currency: "Dollar",
      bio: null,
      profile_picture: null,
      is_favorite: false,
    },
  },
  {
    id: "84",
    type: "stylist",
    attributes: {
      activated: true,
      country_code: null,
      email: "stylist0410@yopmail.com",
      first_name: null,
      full_phone_number: "",
      last_name: null,
      full_name: "stylist",
      phone_number: null,
      type: "SocialAccount",
      created_at: "2023-10-04T12:10:50.830Z",
      updated_at: "2023-10-04T12:10:50.830Z",
      device_id: null,
      unique_auth_id: "12345445",
      driver_status: "offline",
      seller_status: "Signup",
      approve_status: "Pending",
      language: "English",
      currency: "Dollar",
      bio: null,
      profile_picture: null,
      is_favorite: false,
    },
  },
  {
    id: "94",
    type: "stylist",
    attributes: {
      activated: true,
      country_code: null,
      email: "sfdfhdller@yopmail.com",
      first_name: null,
      full_phone_number: "",
      last_name: null,
      full_name: "stylist",
      phone_number: null,
      type: "SocialAccount",
      created_at: "2023-10-05T12:54:14.238Z",
      updated_at: "2023-10-05T12:54:14.238Z",
      device_id: null,
      unique_auth_id: "12345765",
      driver_status: "offline",
      seller_status: "Signup",
      approve_status: "Pending",
      language: "English",
      currency: "Dollar",
      bio: null,
      profile_picture: null,
      is_favorite: false,
    },
  },
  {
    id: "74",
    type: "stylist",
    attributes: {
      activated: false,
      country_code: null,
      email: "tett1222@yopmail.com",
      first_name: null,
      full_phone_number: "91",
      last_name: null,
      full_name: "Test QA MINE",
      phone_number: null,
      type: null,
      created_at: "2023-09-21T11:29:24.697Z",
      updated_at: "2023-10-17T09:00:33.684Z",
      device_id: null,
      unique_auth_id: "KMi8nT7RzfR82eHqHg0ktgtt",
      driver_status: "offline",
      seller_status: "Signup",
      approve_status: "Pending",
      language: "English",
      currency: "Dollar",
      bio: null,
      profile_picture: null,
      is_favorite: false,
    },
  },
  {
    id: "95",
    type: "stylist",
    attributes: {
      activated: true,
      country_code: null,
      email: "stylist13@yopmail.com",
      first_name: null,
      full_phone_number: "",
      last_name: null,
      full_name: "stylist1",
      phone_number: null,
      type: "SocialAccount",
      created_at: "2023-10-06T07:20:13.726Z",
      updated_at: "2023-10-06T07:20:13.726Z",
      device_id: null,
      unique_auth_id: "12345445",
      driver_status: "offline",
      seller_status: "Signup",
      approve_status: "Pending",
      language: "English",
      currency: "Dollar",
      bio: null,
      profile_picture: null,
      is_favorite: false,
    },
  },
  {
    id: "92",
    type: "stylist",
    attributes: {
      activated: true,
      country_code: null,
      email: "chandnii1@gmail.com",
      first_name: null,
      full_phone_number: "",
      last_name: null,
      full_name: "ch1",
      phone_number: null,
      type: "SocialAccount",
      created_at: "2023-10-05T10:45:34.828Z",
      updated_at: "2023-10-05T11:58:34.730Z",
      device_id: null,
      unique_auth_id: "12345445",
      driver_status: "offline",
      seller_status: "Signup",
      approve_status: "Pending",
      language: "English",
      currency: "Dollar",
      bio: null,
      profile_picture: null,
      is_favorite: false,
    },
  },
  {
    id: "97",
    type: "stylist",
    attributes: {
      activated: true,
      country_code: null,
      email: "1stylist@yopmail.com",
      first_name: null,
      full_phone_number: "",
      last_name: null,
      full_name: "stylist",
      phone_number: null,
      type: "SocialAccount",
      created_at: "2023-10-06T09:44:42.631Z",
      updated_at: "2023-10-06T09:44:42.631Z",
      device_id: null,
      unique_auth_id: "12345765",
      driver_status: "offline",
      seller_status: "Signup",
      approve_status: "Pending",
      language: "English",
      currency: "Dollar",
      bio: null,
      profile_picture: null,
      is_favorite: false,
    },
  },
  {
    id: "105",
    type: "stylist",
    attributes: {
      activated: true,
      country_code: null,
      email: "stylist1s3@yopmail.com",
      first_name: null,
      full_phone_number: "",
      last_name: null,
      full_name: "stylist12",
      phone_number: null,
      type: "SocialAccount",
      created_at: "2023-10-06T10:10:09.719Z",
      updated_at: "2023-10-06T10:10:09.719Z",
      device_id: null,
      unique_auth_id: "12345765",
      driver_status: "offline",
      seller_status: "Signup",
      approve_status: "Pending",
      language: "English",
      currency: "Dollar",
      bio: null,
      profile_picture: null,
      is_favorite: false,
    },
  },
  {
    id: "117",
    type: "stylist",
    attributes: {
      activated: true,
      country_code: null,
      email: "stylist12e3@yopmail.com",
      first_name: null,
      full_phone_number: "",
      last_name: null,
      full_name: "stylist11",
      phone_number: null,
      type: "SocialAccount",
      created_at: "2023-10-09T10:39:52.707Z",
      updated_at: "2023-10-09T10:39:52.707Z",
      device_id: null,
      unique_auth_id: "12345765",
      driver_status: "offline",
      seller_status: "Signup",
      approve_status: "Pending",
      language: "English",
      currency: "Dollar",
      bio: null,
      profile_picture: null,
      is_favorite: false,
    },
  },
  {
    id: "118",
    type: "stylist",
    attributes: {
      activated: true,
      country_code: null,
      email: "2stylist@yopmail.com",
      first_name: null,
      full_phone_number: "",
      last_name: null,
      full_name: "Stylist",
      phone_number: null,
      type: "SocialAccount",
      created_at: "2023-10-10T04:36:33.383Z",
      updated_at: "2023-10-10T04:36:33.383Z",
      device_id: null,
      unique_auth_id: "12345765",
      driver_status: "offline",
      seller_status: "Signup",
      approve_status: "Pending",
      language: "English",
      currency: "Dollar",
      bio: "nn",
      profile_picture: null,
      is_favorite: false,
    },
  },
  {
    id: "126",
    type: "stylist",
    attributes: {
      activated: false,
      country_code: "91",
      email: "testverified@yopmail.com",
      first_name: null,
      full_phone_number: "919892648862",
      last_name: null,
      full_name: "Test Verified",
      phone_number: "9892648862",
      type: null,
      created_at: "2023-10-17T09:10:46.677Z",
      updated_at: "2023-10-17T09:10:46.677Z",
      device_id: null,
      unique_auth_id: "4wvcEaeFI1kXefQJQ5Dzmwtt",
      driver_status: "offline",
      seller_status: "Signup",
      approve_status: "Pending",
      language: "English",
      currency: "Dollar",
      bio: null,
      profile_picture: null,
      is_favorite: false,
    },
  },
  {
    id: "128",
    type: "stylist",
    attributes: {
      activated: false,
      country_code: "91",
      email: "testverified1@yopmail.com",
      first_name: null,
      full_phone_number: "919692648862",
      last_name: null,
      full_name: "Test Verified",
      phone_number: "9692648862",
      type: null,
      created_at: "2023-10-17T10:37:42.433Z",
      updated_at: "2023-10-17T10:37:42.433Z",
      device_id: null,
      unique_auth_id: "vu8PeDdtvSEkYjrdiF9rYQtt",
      driver_status: "offline",
      seller_status: "Signup",
      approve_status: "Pending",
      language: "English",
      currency: "Dollar",
      bio: null,
      profile_picture: null,
      is_favorite: false,
    },
  },
  {
    id: "131",
    type: "stylist",
    attributes: {
      activated: true,
      country_code: "91",
      email: "st14@yopmail.com",
      first_name: null,
      full_phone_number: "918980718827",
      last_name: null,
      full_name: "STl",
      phone_number: "8980718827",
      type: null,
      created_at: "2023-10-18T04:42:28.014Z",
      updated_at: "2023-10-18T06:09:47.803Z",
      device_id: null,
      unique_auth_id: "3roBrYlXphFQKX8qrhk3xwtt",
      driver_status: "offline",
      seller_status: "Signup",
      approve_status: "Pending",
      language: "English",
      currency: "Dollar",
      bio: null,
      profile_picture: null,
      is_favorite: false,
    },
  },
  {
    id: "143",
    type: "stylist",
    attributes: {
      activated: true,
      country_code: null,
      email: "stylebyhm14@yopmail.com",
      first_name: null,
      full_phone_number: "",
      last_name: null,
      full_name: "StlHM",
      phone_number: null,
      type: "SocialAccount",
      created_at: "2023-10-19T05:27:47.782Z",
      updated_at: "2023-10-19T05:27:47.782Z",
      device_id: null,
      unique_auth_id: "12345765",
      driver_status: "offline",
      seller_status: "Signup",
      approve_status: "Pending",
      language: "English",
      currency: "Dollar",
      bio: null,
      profile_picture: null,
      is_favorite: false,
    },
  },
  {
    id: "151",
    type: "stylist",
    attributes: {
      activated: false,
      country_code: "91",
      email: "hdfbjn@gmail.com",
      first_name: null,
      full_phone_number: "919283766543",
      last_name: null,
      full_name: "dhbbdjhffvffv",
      phone_number: "9283766543",
      type: null,
      created_at: "2023-10-22T17:39:31.627Z",
      updated_at: "2023-10-22T17:39:31.627Z",
      device_id: null,
      unique_auth_id: "5YBkZcNjvNa7qJilam2mEAtt",
      driver_status: "offline",
      seller_status: "Signup",
      approve_status: "Pending",
      language: "English",
      currency: "Dollar",
      bio: null,
      profile_picture: null,
      is_favorite: false,
    },
  },
  {
    id: "315",
    type: "stylist",
    attributes: {
      activated: true,
      country_code: null,
      email: "2stylist1@yopmail.com",
      first_name: null,
      full_phone_number: null,
      last_name: null,
      full_name: "Stylist",
      phone_number: null,
      type: "SocialAccount",
      created_at: "2023-11-21T12:12:42.227Z",
      updated_at: "2023-11-21T12:12:42.227Z",
      device_id: null,
      unique_auth_id: "12345765",
      driver_status: "offline",
      seller_status: "Signup",
      approve_status: "Pending",
      language: "English",
      currency: "Dollar",
      bio: null,
      profile_picture: null,
      is_favorite: false,
    },
  },
  {
    id: "344",
    type: "stylist",
    attributes: {
      activated: true,
      country_code: null,
      email: "driver@yopmail.com",
      first_name: null,
      full_phone_number: null,
      last_name: null,
      full_name: "driver",
      phone_number: null,
      type: "SocialAccount",
      created_at: "2023-12-05T04:02:06.926Z",
      updated_at: "2023-12-05T04:02:06.926Z",
      device_id: null,
      unique_auth_id: "12345765",
      driver_status: "offline",
      seller_status: "Signup",
      approve_status: "Pending",
      language: "English",
      currency: "Dollar",
      bio: null,
      profile_picture: null,
      is_favorite: false,
    },
  },
];

export const stylistResponse = {
  data: stylistArr,
  meta: {
    total_pages: 5,
    current_page: 1,
    total_record: 88,
    prev_page: null,
    next_page: 2,
  },
};


export const MyBidsData = {
  "data": [
      {
          "id": "22",
          "type": "product_sourcing_stylist_price",
          "attributes": {
              "id": 22,
              "request_id": 41,
              "account_id": 972,
              "quote_price": 30.0,
              "product_description": "this is test",
              "request_status": "accepted",
              "created_at": "2024-07-23T09:27:02.379Z",
              "updated_at": "2024-07-25T05:27:10.487Z",
              "full_name": "fashion fashion",
              "images": [
                  {
                      "id": 3860,
                      "url": "image.jpg"
                  }
              ],
              "product_sourcing_request": {
                  "id": 41,
                  "product_name": "Catalogue_Winter",
                  "sizes": [
                      "small",
                      "medium",
                      "large"
                  ],
                  "colours": [
                      "black",
                      "blue"
                  ],
                  "gender": "male",
                  "min_price": "20.0",
                  "max_price": "50.0",
                  "quantity": 1,
                  "request_status": "accepted",
                  "description": "gfdgfd gfdgfdgfdggf gfdgfgtrevdfdf dfgfgf",
                  "created_at": "2024-07-22T13:41:48.876Z",
                  "updated_at": "2024-07-25T05:27:10.504Z",
                  "images": [
                      {
                          "id": 3852,
                          "url": "unsplash.jpg"
                      }
                  ]
              }
          }
      },
      {
          "id": "9",
          "type": "product_sourcing_stylist_price",
          "attributes": {
              "id": 9,
              "request_id": 25,
              "account_id": 972,
              "quote_price": 10.0,
              "product_description": "lorem_ipsum",
              "request_status": "rejected",
              "created_at": "2024-07-16T11:02:13.675Z",
              "updated_at": "2024-07-18T11:04:36.470Z",
              "full_name": "fashion fashion",
              "images": [
                  {
                      "id": 3661,
                      "url": "FashionAggregator.jpg"
                  }
              ],
              "product_sourcing_request": {
                  "id": 25,
                  "product_name": "TEST",
                  "sizes": [
                      "M",
                      "XL"
                  ],
                  "colours": [
                      "RED",
                      "BLACK"
                  ],
                  "gender": "male",
                  "min_price": "10.0",
                  "max_price": "200.0",
                  "quantity": 12,
                  "request_status": "accepted",
                  "description": "JUST FOR TESTING",
                  "created_at": "2024-07-08T10:38:22.111Z",
                  "updated_at": "2024-07-16T11:06:17.954Z",
                  "images": [
                      {
                          "id": 3263,
                          "url": "profile.jpg"
                      }
                  ]
              }
          }
      },
      {
          "id": "10",
          "type": "product_sourcing_stylist_price",
          "attributes": {
              "id": 10,
              "request_id": 33,
              "account_id": 972,
              "quote_price": 100.0,
              "product_description": "this is test",
              "request_status": "waiting",
              "created_at": "2024-07-17T07:47:29.246Z",
              "updated_at": "2024-07-18T11:29:14.847Z",
              "full_name": "fashion fashion",
              "images": [
                  {
                      "id": 3673,
                      "url": "FashionAggregator.jpg"
                  },
                  {
                      "id": 3676,
                      "url": "FashionAggregator.jpg"
                  }
              ],
              "product_sourcing_request": {
                  "id": 33,
                  "product_name": "Night Suit",
                  "sizes": [
                      "L",
                      "XL"
                  ],
                  "colours": [
                      "Any"
                  ],
                  "gender": "male",
                  "min_price": "50.0",
                  "max_price": "100.0",
                  "quantity": 40,
                  "request_status": "accepted",
                  "description": "Best night suite design for Boys design must be comfortable to were",
                  "created_at": "2024-07-17T07:42:04.608Z",
                  "updated_at": "2024-07-18T06:37:32.204Z",
                  "images": [
                      {
                          "id": 3667,
                          "url": "profile.jpg"
                      }
                  ]
              }
          }
      },
  ],
  "meta": {
    "total_pages": 1,
    "current_page": 1,
    "total_record": 3,
    "prev_page": null,
    "next_page": null
}
}

export const sourceProductResponse9Data = {
  data: {
    id: "29",
    type: "sourcing_request",
    attributes: {
      id: 29,
      product_name: "Hsjssj",
      buyer_id : 12,
      request_status: "pending",
      max_price: "600.0",
      min_price: "100.0",
      sizes: ["Xl"],
      description: "Bsjss",
      gender: "female",
      quantity: 300,
      colours: ["Red"],
      images: [
        {
          id: 3532,
          url: "profile.jpg",
        },
      ],
      product_sourcing_stylist_prices: [
        {
          id: 13,
          request_id: 29,
          account_id: 972,
          quote_price: 300.0,
          product_description: "uiosdiouiow eyio eiofy e8o fl ",
          request_status: "accepted",
          created_at: "2024-07-22T10:51:22.440Z",
          updated_at: "2024-07-22T10:51:22.448Z",
          full_name: "fashion fashion",
          images: [
            {
              id: 3815,
              url: "image.jpg",
            },
          ],
        },
      ],
    },
  },
};