export const mockWishlistData = {
  data: [
    {
      id: "267",
      type: "favourite",
      attributes: {
        favouriteable_id: 226,
        favouriteable_type: "BxBlockCatalogue::Catalogue",
        wishlist_id: 16,
        notes: null,
        created_at: "2024-07-01T06:55:47.066Z",
        updated_at: "2024-07-01T06:55:47.066Z",
        favouriteable: {
          data: {
            id: "226",
            type: "catalogue_wishlist",
            attributes: {
              name: "wrerewr",
              brand: null,
              sku: null,
              description: "tretretret",
              manufacture_date: null,
              stock_qty: null,
              availability: null,
              price: null,
              discount: null,
              is_wishlist: true,
              product_number: null,
              primary_image:
                "http://example.com/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnNJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ff9c391bfa7cb08c19c604d349cca4f9c805913e/profile.jpg",
              primary_price: "200.0",
              gender: "male",
              brand_name: "rewre",
              material: "45tertrte",
              fit: "trrtrete",
              prodcut_care: "retretreet",
              list_the_product: "listed",
              fit_discription: null,
              primary_size: {
                id: 6,
                name: "M",
                created_at: "2023-10-06T04:45:41.059Z",
                updated_at: "2024-04-24T09:26:43.720Z",
              },
              primary_colour: {
                id: 7,
                name: "Grey",
                created_at: "2023-10-05T05:19:28.122Z",
                updated_at: "2023-10-05T05:19:28.122Z",
              },
            },
          },
        },
      },
    },
    {
      id: "273",
      type: "favourite",
      attributes: {
        favouriteable_id: 208,
        favouriteable_type: "BxBlockCatalogue::Catalogue",
        wishlist_id: 16,
        notes: null,
        created_at: "2024-07-01T07:20:17.580Z",
        updated_at: "2024-07-01T07:20:17.580Z",
        favouriteable: {
          data: {
            id: "208",
            type: "catalogue_wishlist",
            attributes: {
              name: "winter best t shirt",
              brand: null,
              sku: null,
              description: "bbn",
              manufacture_date: null,
              stock_qty: null,
              availability: null,
              price: null,
              discount: null,
              is_wishlist: true,
              product_number: null,
              primary_image:
                "http://example.com/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVlGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cf4c16166068189ad8b443098e0486d755c627d5/profile.jpg",
              primary_price: "46.0",
              gender: "male",
              brand_name: "bjk",
              material: "cotten jfb",
              fit: "hghjj ",
              prodcut_care: "jhfhgf kg kg",
              list_the_product: "listed",
              fit_discription: null,
              primary_size: {
                id: 1,
                name: "Small",
                created_at: "2023-09-22T04:45:35.966Z",
                updated_at: "2023-09-22T04:45:35.966Z",
              },
              primary_colour: {
                id: 7,
                name: "Grey",
                created_at: "2023-10-05T05:19:28.122Z",
                updated_at: "2023-10-05T05:19:28.122Z",
              },
            },
          },
        },
      },
    },
  ],
};

export const mockSuggestionData = {
  data: [
    {
      id: "227",
      type: "catalogue_listing",
      attributes: {
        name: "Abc",
        description: "fgdgfdgfd",
        catalogue_variants: [
          {
            id: "384",
            type: "catalogue_variant",
            attributes: {
              id: 384,
              catalogue_id: 227,
              catalogue_variant_color_id: 7,
              catalogue_variant_color: {
                id: 7,
                name: "Grey",
                created_at: "2023-10-05T05:19:28.122Z",
                updated_at: "2023-10-05T05:19:28.122Z",
              },
              catalogue_variant_size_id: 1,
              catalogue_variant_size: {
                id: 1,
                name: "Small",
                created_at: "2023-09-22T04:45:35.966Z",
                updated_at: "2023-09-22T04:45:35.966Z",
              },
              price: "20.0",
              stock_qty: 5,
              on_sale: null,
              sale_price: null,
              discount_price: null,
              length: null,
              breadth: null,
              height: null,
              created_at: "2024-06-19T07:32:20.465Z",
              updated_at: "2024-06-19T07:32:20.480Z",
              sku: "sp30",
              deactivate: false,
              low_stock_threshold: 0,
              is_listed: true,
              front_image:
                "http://example.com/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjBJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b91971d852ceddb74f98c1be937fe2813a9c1d32/profile.jpg",
              back_image: "",
              side_image: "",
              pair_it_with: [],
            },
          },
          {
            id: "386",
            type: "catalogue_variant",
            attributes: {
              id: 386,
              catalogue_id: 227,
              catalogue_variant_color_id: 12,
              catalogue_variant_color: {
                id: 12,
                name: "Black",
                created_at: "2024-03-06T06:42:44.507Z",
                updated_at: "2024-03-06T06:42:44.507Z",
              },
              catalogue_variant_size_id: 1,
              catalogue_variant_size: {
                id: 1,
                name: "Small",
                created_at: "2023-09-22T04:45:35.966Z",
                updated_at: "2023-09-22T04:45:35.966Z",
              },
              price: "25.0",
              stock_qty: 5,
              on_sale: null,
              sale_price: null,
              discount_price: null,
              length: null,
              breadth: null,
              height: null,
              created_at: "2024-06-19T07:32:20.497Z",
              updated_at: "2024-06-19T07:32:20.511Z",
              sku: "sp23",
              deactivate: false,
              low_stock_threshold: 0,
              is_listed: true,
              front_image:
                "http://example.com/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjhJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1f6ad1af1e7e82c7638892e1f5ffa3e6673d35cb/profile.jpg",
              back_image: "",
              side_image: "",
              pair_it_with: [],
            },
          },
          {
            id: "387",
            type: "catalogue_variant",
            attributes: {
              id: 387,
              catalogue_id: 227,
              catalogue_variant_color_id: 13,
              catalogue_variant_color: {
                id: 13,
                name: "Maroon",
                created_at: "2024-03-27T09:19:36.201Z",
                updated_at: "2024-03-27T09:19:36.201Z",
              },
              catalogue_variant_size_id: 1,
              catalogue_variant_size: {
                id: 1,
                name: "Small",
                created_at: "2023-09-22T04:45:35.966Z",
                updated_at: "2023-09-22T04:45:35.966Z",
              },
              price: "40.0",
              stock_qty: 5,
              on_sale: null,
              sale_price: null,
              discount_price: null,
              length: null,
              breadth: null,
              height: null,
              created_at: "2024-06-19T07:32:20.511Z",
              updated_at: "2024-06-19T07:32:20.524Z",
              sku: "sp20",
              deactivate: false,
              low_stock_threshold: 0,
              is_listed: true,
              front_image:
                "http://example.com/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0FKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1aaada60ccb43d0396e79226824a26db13f9c8c5/profile.jpg",
              back_image: "",
              side_image: "",
              pair_it_with: [],
            },
          },
          {
            id: "390",
            type: "catalogue_variant",
            attributes: {
              id: 390,
              catalogue_id: 227,
              catalogue_variant_color_id: 12,
              catalogue_variant_color: {
                id: 12,
                name: "Black",
                created_at: "2024-03-06T06:42:44.507Z",
                updated_at: "2024-03-06T06:42:44.507Z",
              },
              catalogue_variant_size_id: 9,
              catalogue_variant_size: {
                id: 9,
                name: "Medium",
                created_at: "2024-03-06T05:53:50.617Z",
                updated_at: "2024-03-06T05:53:50.617Z",
              },
              price: "10.0",
              stock_qty: 5,
              on_sale: null,
              sale_price: null,
              discount_price: null,
              length: null,
              breadth: null,
              height: null,
              created_at: "2024-06-19T07:32:20.554Z",
              updated_at: "2024-06-19T07:32:20.570Z",
              sku: "sp6",
              deactivate: false,
              low_stock_threshold: 0,
              is_listed: true,
              front_image:
                "http://example.com/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ01KIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--88a212794910f6409ff2457466669a609fba1396/profile.jpg",
              back_image: "",
              side_image: "",
              pair_it_with: [],
            },
          },
          {
            id: "391",
            type: "catalogue_variant",
            attributes: {
              id: 391,
              catalogue_id: 227,
              catalogue_variant_color_id: 13,
              catalogue_variant_color: {
                id: 13,
                name: "Maroon",
                created_at: "2024-03-27T09:19:36.201Z",
                updated_at: "2024-03-27T09:19:36.201Z",
              },
              catalogue_variant_size_id: 9,
              catalogue_variant_size: {
                id: 9,
                name: "Medium",
                created_at: "2024-03-06T05:53:50.617Z",
                updated_at: "2024-03-06T05:53:50.617Z",
              },
              price: "56.0",
              stock_qty: 5,
              on_sale: null,
              sale_price: null,
              discount_price: null,
              length: null,
              breadth: null,
              height: null,
              created_at: "2024-06-19T07:32:20.570Z",
              updated_at: "2024-06-19T07:32:20.583Z",
              sku: "sp5",
              deactivate: false,
              low_stock_threshold: 0,
              is_listed: true,
              front_image:
                "http://example.com/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ1FKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9a63fd35bbb89c9c18b85c143ae7ca38a66f8fd2/profile.jpg",
              back_image: "",
              side_image: "",
              pair_it_with: [],
            },
          },
          {
            id: "392",
            type: "catalogue_variant",
            attributes: {
              id: 392,
              catalogue_id: 227,
              catalogue_variant_color_id: 7,
              catalogue_variant_color: {
                id: 7,
                name: "Grey",
                created_at: "2023-10-05T05:19:28.122Z",
                updated_at: "2023-10-05T05:19:28.122Z",
              },
              catalogue_variant_size_id: 6,
              catalogue_variant_size: {
                id: 6,
                name: "M",
                created_at: "2023-10-06T04:45:41.059Z",
                updated_at: "2024-04-24T09:26:43.720Z",
              },
              price: "34.0",
              stock_qty: 5,
              on_sale: null,
              sale_price: null,
              discount_price: null,
              length: null,
              breadth: null,
              height: null,
              created_at: "2024-06-19T07:32:20.584Z",
              updated_at: "2024-06-19T07:32:20.596Z",
              sku: "sp4",
              deactivate: false,
              low_stock_threshold: 0,
              is_listed: true,
              front_image:
                "http://example.com/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ1VKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--41b65c09d3bab056e9ee4a979465aa40d739a255/profile.jpg",
              back_image: "",
              side_image: "",
              pair_it_with: [],
            },
          },
          {
            id: "393",
            type: "catalogue_variant",
            attributes: {
              id: 393,
              catalogue_id: 227,
              catalogue_variant_color_id: 10,
              catalogue_variant_color: {
                id: 10,
                name: "Whiteee",
                created_at: "2023-10-05T05:20:08.849Z",
                updated_at: "2023-10-05T05:20:08.849Z",
              },
              catalogue_variant_size_id: 6,
              catalogue_variant_size: {
                id: 6,
                name: "M",
                created_at: "2023-10-06T04:45:41.059Z",
                updated_at: "2024-04-24T09:26:43.720Z",
              },
              price: "40.0",
              stock_qty: 5,
              on_sale: null,
              sale_price: null,
              discount_price: null,
              length: null,
              breadth: null,
              height: null,
              created_at: "2024-06-19T07:32:20.597Z",
              updated_at: "2024-06-19T07:32:20.611Z",
              sku: "sp3",
              deactivate: false,
              low_stock_threshold: 0,
              is_listed: true,
              front_image:
                "http://example.com/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ1lKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--10f87f68991c445a01b6cc9bf12f28774c54246a/profile.jpg",
              back_image: "",
              side_image: "",
              pair_it_with: [],
            },
          },
          {
            id: "394",
            type: "catalogue_variant",
            attributes: {
              id: 394,
              catalogue_id: 227,
              catalogue_variant_color_id: 12,
              catalogue_variant_color: {
                id: 12,
                name: "Black",
                created_at: "2024-03-06T06:42:44.507Z",
                updated_at: "2024-03-06T06:42:44.507Z",
              },
              catalogue_variant_size_id: 6,
              catalogue_variant_size: {
                id: 6,
                name: "M",
                created_at: "2023-10-06T04:45:41.059Z",
                updated_at: "2024-04-24T09:26:43.720Z",
              },
              price: "30.0",
              stock_qty: 5,
              on_sale: null,
              sale_price: null,
              discount_price: null,
              length: null,
              breadth: null,
              height: null,
              created_at: "2024-06-19T07:32:20.612Z",
              updated_at: "2024-06-19T07:32:20.626Z",
              sku: "sp2",
              deactivate: false,
              low_stock_threshold: 0,
              is_listed: true,
              front_image:
                "http://example.com/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ2NKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--04eea7f89b8db7ca974493a2ed74e930617d9455/profile.jpg",
              back_image: "",
              side_image: "",
              pair_it_with: [],
            },
          },
          {
            id: "388",
            type: "catalogue_variant",
            attributes: {
              id: 388,
              catalogue_id: 227,
              catalogue_variant_color_id: 7,
              catalogue_variant_color: {
                id: 7,
                name: "Grey",
                created_at: "2023-10-05T05:19:28.122Z",
                updated_at: "2023-10-05T05:19:28.122Z",
              },
              catalogue_variant_size_id: 9,
              catalogue_variant_size: {
                id: 9,
                name: "Medium",
                created_at: "2024-03-06T05:53:50.617Z",
                updated_at: "2024-03-06T05:53:50.617Z",
              },
              price: "40.0",
              stock_qty: 1,
              on_sale: null,
              sale_price: null,
              discount_price: null,
              length: null,
              breadth: null,
              height: null,
              created_at: "2024-06-19T07:32:20.525Z",
              updated_at: "2024-06-27T10:08:11.397Z",
              sku: "sp24",
              deactivate: false,
              low_stock_threshold: 0,
              is_listed: true,
              front_image:
                "http://example.com/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0VKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--339dd80f28a8b98bf20e8b4b09040fccf955e9c5/profile.jpg",
              back_image: "",
              side_image: "",
              pair_it_with: [],
            },
          },
          {
            id: "395",
            type: "catalogue_variant",
            attributes: {
              id: 395,
              catalogue_id: 227,
              catalogue_variant_color_id: 13,
              catalogue_variant_color: {
                id: 13,
                name: "Maroon",
                created_at: "2024-03-27T09:19:36.201Z",
                updated_at: "2024-03-27T09:19:36.201Z",
              },
              catalogue_variant_size_id: 6,
              catalogue_variant_size: {
                id: 6,
                name: "M",
                created_at: "2023-10-06T04:45:41.059Z",
                updated_at: "2024-04-24T09:26:43.720Z",
              },
              price: "20.0",
              stock_qty: 4,
              on_sale: null,
              sale_price: null,
              discount_price: null,
              length: null,
              breadth: null,
              height: null,
              created_at: "2024-06-19T07:32:20.627Z",
              updated_at: "2024-06-26T13:28:45.960Z",
              sku: "sp1",
              deactivate: false,
              low_stock_threshold: 0,
              is_listed: true,
              front_image:
                "http://example.com/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ2dKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d45043cb980ad89d218afeeb460d49aeb9409f36/profile.jpg",
              back_image: "",
              side_image: "",
              pair_it_with: [
                {
                  id: "386",
                  type: "inventory_management",
                  attributes: {
                    id: 386,
                    catalogue_id: 227,
                    product_name: "Abc",
                    product_description: "fgdgfdgfd",
                    sku: "sp23",
                    stock_qty: 5,
                    low_stock_threshold: 0,
                    is_listed: true,
                    price: "25.0",
                    size: "Small",
                    colour: "Black",
                    gender: "male",
                    front_image:
                      "http://example.com/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjhJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1f6ad1af1e7e82c7638892e1f5ffa3e6673d35cb/profile.jpg",
                    brand_name: "abcd",
                  },
                },
              ],
            },
          },
          {
            id: "389",
            type: "catalogue_variant",
            attributes: {
              id: 389,
              catalogue_id: 227,
              catalogue_variant_color_id: 10,
              catalogue_variant_color: {
                id: 10,
                name: "Whiteee",
                created_at: "2023-10-05T05:20:08.849Z",
                updated_at: "2023-10-05T05:20:08.849Z",
              },
              catalogue_variant_size_id: 9,
              catalogue_variant_size: {
                id: 9,
                name: "Medium",
                created_at: "2024-03-06T05:53:50.617Z",
                updated_at: "2024-03-06T05:53:50.617Z",
              },
              price: "30.0",
              stock_qty: 3,
              on_sale: null,
              sale_price: null,
              discount_price: null,
              length: null,
              breadth: null,
              height: null,
              created_at: "2024-06-19T07:32:20.538Z",
              updated_at: "2024-06-26T04:09:10.569Z",
              sku: "sp7",
              deactivate: false,
              low_stock_threshold: 0,
              is_listed: true,
              front_image:
                "http://example.com/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ0lKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--62fa3ffeca1ea7976538bf326ba255458d204c15/profile.jpg",
              back_image: "",
              side_image: "",
              pair_it_with: [],
            },
          },
          {
            id: "385",
            type: "catalogue_variant",
            attributes: {
              id: 385,
              catalogue_id: 227,
              catalogue_variant_color_id: 10,
              catalogue_variant_color: {
                id: 10,
                name: "Whiteee",
                created_at: "2023-10-05T05:20:08.849Z",
                updated_at: "2023-10-05T05:20:08.849Z",
              },
              catalogue_variant_size_id: 1,
              catalogue_variant_size: {
                id: 1,
                name: "Small",
                created_at: "2023-09-22T04:45:35.966Z",
                updated_at: "2023-09-22T04:45:35.966Z",
              },
              price: "20.0",
              stock_qty: 5,
              on_sale: null,
              sale_price: null,
              discount_price: null,
              length: null,
              breadth: null,
              height: null,
              created_at: "2024-06-19T07:32:20.481Z",
              updated_at: "2024-06-27T06:06:05.686Z",
              sku: "s0l",
              deactivate: false,
              low_stock_threshold: 0,
              is_listed: true,
              front_image:
                "http://example.com/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjRJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eb5eb4dab3252f6e73fa2fd5a91c6b66a6526d2d/profile.jpg",
              back_image: "",
              side_image: "",
              pair_it_with: [],
            },
          },
        ],
        primary_image:
          "http://example.com/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjBJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b91971d852ceddb74f98c1be937fe2813a9c1d32/profile.jpg",
        primary_price: "20.0",
        is_wishlist: false,
      },
    },
  ],
  meta: {
    total_pages: 13,
    current_page: 1,
    total_record: 77,
    prev_page: null,
    next_page: 2,
  },
};
