export const mockCountResponse = {
  total_orders: 15,
  total_shipped_orders: 2,
  total_delivered_orders: 2,
  total_rejected_orders: 3,
  total_process_orders: 2,
  total_in_process_orders: 2,
  total_new_orders: 2,
  total_return_refund_orders: 2,
};

export const mockAllOrdersResponse = {
  orders: {
    data: [
      {
        id: "679",
        type: "seller_order_seller",
        attributes: {
          id: 679,
          status: "return_in_process",
          accept_order_upload_time: null,
          order_items: [
            {
              id: "1211",
              type: "order_item_seller",
              attributes: {
                status: "return_confirmed",
                placed_at: "2024-07-12T09:38:37.917Z",
                confirmed_at: "2024-07-12T09:39:10.443Z",
                in_transit_at: "2024-07-12T09:51:09.225Z",
                delivered_at: "2024-07-12T09:52:13.526Z",
                cancelled_at: null,
                rejected_at: null,
                process_at: "2024-07-12T09:49:48.960Z",
                shipped_at: "2024-07-12T09:50:29.020Z",
                return_at: null,
                return_cancel_at: null,
                return_pick_at: null,
                return_placed_at: "2024-07-15T05:28:04.105Z",
                return_confirmed_at: "2024-07-17T06:26:53.415Z",
                return_reject_at: null,
                returned_assign_at: null,
                quantity: 1,
                unit_price: "29.0",
                total_price: "29.0",
                reason_of_rejection: null,
                catalogue_name: "Show Time Fighter Edition TShirt",
                brand_name: "Show Time",
                catalogue_variant_color: "Red",
                catalogue_variant_sku: "ST000002",
                store_name: "Show Time",
                catalogue_variant_size: "Medium",
                catalogue_variant_front_image:
                  "https://example.com/profile.jpg",
                catalogue_variant_back_image: "",
                catalogue_variant_side_image: "",
                driver_name: null,
                driver_latitude: null,
                driver_longitude: null,
                driver_phone_number: null,
                otp: null,
              },
            },
          ],
          order_management_order: {
            id: "885",
            type: "order_seller_side",
            attributes: {
              order_number: "OD00000031",
              account: "Stingy Buyer",
              sub_total: "29.0",
              total: "93.22",
              status: "return_order",
              placed_at: "2024-07-12T09:38:37.881Z",
              confirmed_at: "2024-07-12T09:39:10.462Z",
              in_transit_at: "2024-07-12T09:51:09.259Z",
              delivered_at: "2024-07-12T09:52:13.613Z",
              cancelled_at: null,
              refunded_at: null,
              returned_at: null,
              deliver_by: null,
              order_status_id: 2,
              created_at: "2024-07-12T09:37:08.663Z",
              updated_at: "2024-07-15T05:28:04.143Z",
              order_deliver_date: null,
              order_deliver_time: null,
              delivery_addresses: {
                id: "499",
                type: "delivery_address",
                attributes: {
                  name: "Stingy Buyer",
                  country_code: "+965",
                  phone_number: "22658956",
                  contact_number: "+96522658956",
                  street: "I Don't know",
                  zip_code: "",
                  area: "Nachinda ",
                  block: "Contai",
                  city: null,
                  house_or_building_number: "N/A",
                  address_name: "Home",
                  is_default: true,
                  latitude: 21.8796165,
                  longitude: 87.7513925,
                },
              },
              order_return_date: "30-07-2024",
              order_return_time: "2PM",
              payment_detail: {
                id: 198,
                status: "CAPTURED",
                created_at: "2024-07-12T09:38:37.878Z",
                updated_at: "2024-07-12T09:38:37.978Z",
                charge_id: "chg_TS01A1320241237l4KP1207166",
                merchant_id: null,
                order_id: "OD00000031",
                amount: 93,
                currency: "KWD",
                customer_id: "cus_TS01A1720241056c6KD1207550",
                reason: "",
                account_id: 1016,
                order_management_order_id: 885,
                refund_id: null,
                refund_amount: null,
                refund_reason: null,
                seller_order_id: null,
                last_four_card_digit: "0008",
                payment_type: "MASTERCARD",
                deleted: false,
              },
            },
          },
        },
      },
    ],
  },
};

export const mockNewOrderResponse = {
  "orders": {
      "data": [
          {
              "id": "1124",
              "type": "seller_order_seller",
              "attributes": {
                  "id": 1124,
                  "order_wait_time":1,
                  "status": "new_order",
                  "accept_order_upload_time": null,
                  "status_humanize": "New order",
                  "order_items": [
                      {
                          "id": "1900",
                          "type": "order_item_seller",
                          "attributes": {
                              "status": "placed",
                              "placed_at": "2024-08-26T09:08:26.011Z",
                              "confirmed_at": null,
                              "in_transit_at": null,
                              "delivered_at": null,
                              "cancelled_at": null,
                              "rejected_at": null,
                              "process_at": null,
                              "shipped_at": null,
                              "return_at": null,
                              "return_cancel_at": null,
                              "return_pick_at": null,
                              "return_placed_at": null,
                              "return_confirmed_at": null,
                              "return_reject_at": null,
                              "returned_assign_at": null,
                              "quantity": 1,
                              "unit_price": "29.0",
                              "total_price": "29.0",
                              "reason_of_rejection": null,
                              "reason_of_return": null,
                              "refunded_cancel_at": null,
                              "reason_refunded_cancel": null,
                              "refunded_at": null,
                              "return_type": null,
                              "status_humanize": "Placed",
                              "catalogue_name": "Show Time Merchandise",
                              "brand_name": "ShowTime",
                              "catalogue_variant_color": "Black",
                              "catalogue_variant_sku": "ST00001",
                              "catalogue_variant_size": "Medium",
                              "catalogue_variant_front_image": "profile.jpg",
                              "catalogue_variant_back_image": "",
                              "catalogue_variant_side_image": "",
                              "driver_name": null,
                              "driver_latitude": null,
                              "driver_longitude": null,
                              "driver_phone_number": null,
                              "otp": null,
                              "store_name": "Show Time"
                          }
                      }
                  ],
                  "order_management_order": {
                      "id": "1490",
                      "type": "order_seller_side",
                      "attributes": {
                          "order_number": "OD00000584",
                          "account": "Test Test",
                          "sub_total": "29.0",
                          "total": "93.22",
                          "status": "placed",
                          "placed_at": "2024-08-26T09:08:25.950Z",
                          "confirmed_at": null,
                          "in_transit_at": null,
                          "delivered_at": null,
                          "cancelled_at": null,
                          "refunded_at": null,
                          "returned_at": null,
                          "deliver_by": null,
                          "order_status_id": 2,
                          "created_at": "2024-08-26T09:06:49.354Z",
                          "updated_at": "2024-08-26T09:08:25.987Z",
                          "order_deliver_date": null,
                          "order_deliver_time": null,
                          "delivery_addresses": {
                              "id": "911",
                              "type": "delivery_address",
                              "attributes": {
                                  "name": "Priyanh",
                                  "country_code": "+91",
                                  "phone_number": "8899787678",
                                  "contact_number": "+918899787678",
                                  "street": "Indore, Madhya Pradesh, India",
                                  "zip_code": "452002",
                                  "area": "New area",
                                  "block": "Block",
                                  "city": null,
                                  "house_or_building_number": "34",
                                  "address_name": "Home",
                                  "is_default": true,
                                  "latitude": 22.7195687,
                                  "longitude": 75.8577258
                              }
                          },
                          "order_return_date": null,
                          "order_return_time": null,
                          "returned_assign_at": null,
                          "refunded_cancel_at": null,
                          "reason_refunded_cancel": null,
                          "status_humanize": "Placed",
                          "payment_detail": {
                              "id": 506,
                              "status": "CAPTURED",
                              "created_at": "2024-08-26T09:08:25.946Z",
                              "updated_at": "2024-08-26T09:08:26.073Z",
                              "charge_id": "chg_TS01A5820241206Pi9h2608208",
                              "merchant_id": null,
                              "order_id": "OD00000584",
                              "amount": "93.0",
                              "currency": "KWD",
                              "customer_id": "cus_TS01A3020240737Rt472208565",
                              "reason": "",
                              "account_id": 1082,
                              "order_management_order_id": 1490,
                              "refund_id": null,
                              "refund_amount": "0.0",
                              "refund_reason": null,
                              "seller_order_id": null,
                              "last_four_card_digit": "4242",
                              "payment_type": "VISA",
                              "deleted": false
                          }
                      }
                  }
              }
          }
      ]
  }
}
export function mockReturnOrderResponse(status: string, nested = true) {
  const data = [
    {
      id: "679",
      type: "seller_order_seller",
      attributes: {
        id: 679,
        status,
        accept_order_upload_time: null,
        order_items: [
          {
            id: "1211",
            type: "order_item_seller",
            attributes: {
              status: "return_confirmed",
              placed_at: "2024-07-12T09:38:37.917Z",
              confirmed_at: "2024-07-12T09:39:10.443Z",
              in_transit_at: "2024-07-12T09:51:09.225Z",
              delivered_at: "2024-07-12T09:52:13.526Z",
              cancelled_at: null,
              rejected_at: null,
              process_at: "2024-07-12T09:49:48.960Z",
              shipped_at: "2024-07-12T09:50:29.020Z",
              return_at: null,
              return_cancel_at: null,
              return_pick_at: null,
              return_placed_at: "2024-07-15T05:28:04.105Z",
              return_confirmed_at: "2024-07-17T06:26:53.415Z",
              return_reject_at: null,
              returned_assign_at: null,
              return_type:"self_drop_off",
              quantity: 1,
              unit_price: "29.0",
              total_price: "29.0",
              reason_of_rejection: null,
              brand_name: "Show Time",
              catalogue_variant_color: "Red",
              catalogue_variant_sku: "ST000002",
              store_name: "Show Time",
              catalogue_variant_size: "Medium",
              catalogue_variant_back_image: "",
              catalogue_variant_side_image: "",
              driver_name: null,
              driver_latitude: null,
              driver_longitude: null,
              driver_phone_number: null,
              otp: null,
              catalogue:{attributes:{name:'anem'}},
              catalogue_variant:{attributes:{front_image:'iamgewe'}}
            },
          },
        ],
        order_management_order: {
          id: "885",
          type: "order_seller_side",
          attributes: {
            order_number: "OD00000031",
            account: "Stingy Buyer",
            sub_total: "29.0",
            total: "93.22",
            status: "return_order",
            placed_at: "2024-07-12T09:38:37.881Z",
            confirmed_at: "2024-07-12T09:39:10.462Z",
            in_transit_at: "2024-07-12T09:51:09.259Z",
            delivered_at: "2024-07-12T09:52:13.613Z",
            cancelled_at: null,
            refunded_at: null,
            returned_at: null,
            deliver_by: null,
            order_status_id: 2,
            created_at: "2024-07-12T09:37:08.663Z",
            updated_at: "2024-07-15T05:28:04.143Z",
            order_deliver_date: null,
            order_deliver_time: null,
            delivery_addresses: {
              id: "499",
              type: "delivery_address",
              attributes: {
                name: "Stingy Buyer",
                country_code: "+965",
                phone_number: "22658956",
                contact_number: "+96522658956",
                street: "India",
                zip_code: "",
                area: "Nachinda ",
                block: "Contai",
                city: null,
                house_or_building_number: "N/A",
                address_name: "Home",
                is_default: true,
                latitude: 21.8796165,
                longitude: 87.7513925,
              },
            },
            order_return_date: "30-07-2024",
            order_return_time: "2PM",
            payment_detail: {
              id: 198,
              status: "CAPTURED",
              created_at: "2024-07-12T09:38:37.878Z",
              updated_at: "2024-07-12T09:38:37.978Z",
              charge_id: "chg_TS01A1320241237l4KP1207166",
              merchant_id: null,
              order_id: "OD00000031",
              amount: 93,
              currency: "KWD",
              customer_id: "cus_TS01A1720241056c6KD1207550",
              reason: "",
              account_id: 1016,
              order_management_order_id: 885,
              refund_id: null,
              refund_amount: null,
              refund_reason: null,
              seller_order_id: null,
              last_four_card_digit: "0008",
              payment_type: "MASTERCARD",
              deleted: false,
            },
          },
        },
      },
    },
  ];
  if (nested) {
    return {
      orders: { data },
    };
  }
  return {
    data,
  };
}
export function createMockData(status: string, nested = true) {
  const data = [
    {
      id: "679",
      type: "seller_order_seller",
      attributes: {
        id: 679,
        status,
        accept_order_upload_time: null,
        order_items: [
          {
            id: "1211",
            type: "order_item_seller",
            attributes: {
              status: "return_confirmed",
              placed_at: "2024-07-12T09:38:37.917Z",
              confirmed_at: "2024-07-12T09:39:10.443Z",
              in_transit_at: "2024-07-12T09:51:09.225Z",
              delivered_at: "2024-07-12T09:52:13.526Z",
              cancelled_at: null,
              rejected_at: null,
              process_at: "2024-07-12T09:49:48.960Z",
              shipped_at: "2024-07-12T09:50:29.020Z",
              return_at: null,
              return_cancel_at: null,
              return_pick_at: null,
              return_placed_at: "2024-07-15T05:28:04.105Z",
              return_confirmed_at: "2024-07-17T06:26:53.415Z",
              return_reject_at: null,
              returned_assign_at: null,
              quantity: 1,
              unit_price: "29.0",
              total_price: "29.0",
              reason_of_rejection: null,
              catalogue_name: "Show Time Fighter Edition TShirt",
              brand_name: "Show Time",
              catalogue_variant_color: "Red",
              catalogue_variant_sku: "ST000002",
              store_name: "Show Time",
              catalogue_variant_size: "Medium",
              catalogue_variant_front_image: "/profile.jpg",
              catalogue_variant_back_image: "",
              catalogue_variant_side_image: "",
              driver_name: null,
              driver_latitude: null,
              driver_longitude: null,
              driver_phone_number: null,
              otp: null,
            },
          },
        ],
        order_management_order: {
          id: "885",
          type: "order_seller_side",
          attributes: {
            order_number: "OD00000031",
            account: "Stingy Buyer",
            sub_total: "29.0",
            total: "93.22",
            status: "return_order",
            placed_at: "2024-07-12T09:38:37.881Z",
            confirmed_at: "2024-07-12T09:39:10.462Z",
            in_transit_at: "2024-07-12T09:51:09.259Z",
            delivered_at: "2024-07-12T09:52:13.613Z",
            cancelled_at: null,
            refunded_at: null,
            returned_at: null,
            deliver_by: null,
            order_status_id: 2,
            created_at: "2024-07-12T09:37:08.663Z",
            updated_at: "2024-07-15T05:28:04.143Z",
            order_deliver_date: null,
            order_deliver_time: null,
            delivery_addresses: {
              id: "499",
              type: "delivery_address",
              attributes: {
                name: "Stingy Buyer",
                country_code: "+965",
                phone_number: "22658956",
                contact_number: "+96522658956",
                street: "India",
                zip_code: "",
                area: "Nachinda ",
                block: "Contai",
                city: null,
                house_or_building_number: "N/A",
                address_name: "Home",
                is_default: true,
                latitude: 21.8796165,
                longitude: 87.7513925,
              },
            },
            order_return_date: "30-07-2024",
            order_return_time: "2PM",
            payment_detail: {
              id: 198,
              status: "CAPTURED",
              created_at: "2024-07-12T09:38:37.878Z",
              updated_at: "2024-07-12T09:38:37.978Z",
              charge_id: "chg_TS01A1320241237l4KP1207166",
              merchant_id: null,
              order_id: "OD00000031",
              amount: 93,
              currency: "KWD",
              customer_id: "cus_TS01A1720241056c6KD1207550",
              reason: "",
              account_id: 1016,
              order_management_order_id: 885,
              refund_id: null,
              refund_amount: null,
              refund_reason: null,
              seller_order_id: null,
              last_four_card_digit: "0008",
              payment_type: "MASTERCARD",
              deleted: false,
            },
          },
        },
      },
    },
  ];
  if (nested) {
    return {
      orders: { data },
    };
  }
  return {
    data,
  };
}
