export const dummyCart = {
  data: {
    id: "67",
    type: "order",
    attributes: {
      id: 67,
      order_number: "OD00000057",
      title: "Order Summary",
      amount: null,
      order_item_count: 1,
      account_id: 423,
      coupon_code_id: null,
      delivery_address_id: null,
      sub_total: "2008.0",
      total: "2369.44",
      status: "created",
      custom_label: null,
      applied_discount: "0.0",
      cancellation_reason: null,
      order_date: null,
      is_gift: false,
      placed_at: null,
      confirmed_at: null,
      in_transit_at: null,
      delivered_at: null,
      cancelled_at: null,
      refunded_at: null,
      source: null,
      shipment_id: null,
      delivery_charges: null,
      tracking_url: null,
      schedule_time: null,
      payment_failed_at: null,
      payment_pending_at: null,
      returned_at: null,
      tax_charges: "0.0",
      deliver_by: null,
      tracking_number: null,
      is_error: false,
      delivery_error_message: null,
      order_status_id: 1,
      is_group: true,
      is_availability_checked: false,
      shipping_charge: "50.0",
      shipping_discount: "50.0",
      shipping_net_amt: "0.0",
      shipping_total: "0.0",
      total_tax: 361.44,
      created_at: "2024-02-07T13:23:56.301Z",
      updated_at: "2024-02-12T06:05:23.458Z",
      order_deliver_date: null,
      order_deliver_time: null,
      delivery_addresses: [],
      order_return_date: null,
      order_return_time: null,
      razorpay_order_id: null,
      charged: null,
      invoice_id: null,
      invoiced: null,
      order_items: [
        {
          id: "89",
          type: "order_item",
          attributes: {
            id: 89,
            order_management_order_id: 67,
            variant_availability: "available",
            quantity: 2,
            unit_price: "1004.0",
            total_price: "2008.0",
            old_unit_price: null,
            status: "in_cart",
            catalogue_id: 105,
            catalogue_variant_id: 124,
            order_status_id: 1,
            placed_at: null,
            confirmed_at: null,
            in_transit_at: null,
            delivered_at: null,
            cancelled_at: null,
            refunded_at: null,
            manage_placed_status: false,
            manage_cancelled_status: false,
            created_at: "2024-02-07T13:23:56.415Z",
            updated_at: "2024-02-12T06:05:23.432Z",
            reason_of_rejection: null,
            rejected_at: null,
            estimated_delivery_time: "2024-02-14T06:05:56.589Z",
            order_statuses: {
              order_number: "OD00000057",
              placed_at: null,
              confirmed_at: null,
              in_transit_at: null,
              delivered_at: null,
              cancelled_at: null,
              refunded_at: null,
            },
          },
        },
      ],
    },
  },
};

export const CatalogueListMockData = {
  data: [
    {
      id: "225",
      type: "catalogue_listing",
      attributes: {
        name: "Summer_Shorts",
        description: "it's a denim cotton shorts\r\n",
        catalogue_variants: [
          {
            id: "379",
            type: "catalogue_variant",
            attributes: {
              id: 379,
              catalogue_id: 225,
              catalogue_variant_color_id: 16,
              catalogue_variant_color: {
                id: 16,
                name: "Blue",
                created_at: "2024-03-29T11:17:50.262Z",
                updated_at: "2024-03-29T11:17:50.262Z",
              },
              catalogue_variant_size_id: 1,
              catalogue_variant_size: {
                id: 1,
                name: "Small",
                created_at: "2023-09-22T04:45:35.966Z",
                updated_at: "2023-09-22T04:45:35.966Z",
              },
              price: "5400.0",
              stock_qty: 219,
              on_sale: null,
              sale_price: null,
              discount_price: null,
              length: null,
              breadth: null,
              height: null,
              created_at: "2024-05-21T06:04:06.858Z",
              updated_at: "2024-06-21T09:20:51.625Z",
              sku: "F2",
              deactivate: false,
              low_stock_threshold: 0,
              is_listed: true,
              front_image:
                "https://sample.images/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcVVJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d87010f30b0a1ad4fec623313b76d39ed676f3fb/pexels-edgars-kisuro-1488463.jpg",
              back_image: "",
              side_image: "",
              pair_it_with: [],
            },
          },
          {
            id: "380",
            type: "catalogue_variant",
            attributes: {
              id: 380,
              catalogue_id: 225,
              catalogue_variant_color_id: 7,
              catalogue_variant_color: {
                id: 7,
                name: "Grey",
                created_at: "2023-10-05T05:19:28.122Z",
                updated_at: "2023-10-05T05:19:28.122Z",
              },
              catalogue_variant_size_id: 1,
              catalogue_variant_size: {
                id: 1,
                name: "Small",
                created_at: "2023-09-22T04:45:35.966Z",
                updated_at: "2023-09-22T04:45:35.966Z",
              },
              price: "7000.0",
              stock_qty: 861,
              on_sale: null,
              sale_price: null,
              discount_price: null,
              length: null,
              breadth: null,
              height: null,
              created_at: "2024-05-21T11:39:21.975Z",
              updated_at: "2024-06-24T11:30:34.615Z",
              sku: "F9",
              deactivate: false,
              low_stock_threshold: 0,
              is_listed: true,
              front_image: "",
              back_image: "",
              side_image: "",
              pair_it_with: [],
            },
          },
        ],
        primary_image:
          "https://sample.images/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcVVJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d87010f30b0a1ad4fec623313b76d39ed676f3fb/pexels-edgars-kisuro-1488463.jpg",
        primary_price: "5400.0",
        is_wishlist: false,
        primary_discounted_percentage:'0'
      },
    },
    {
      id: "208",
      type: "catalogue_listing",
      attributes: {
        name: "winter best t shirt",
        description: "bbn",
        catalogue_variants: [
          {
            id: "324",
            type: "catalogue_variant",
            attributes: {
              id: 324,
              catalogue_id: 208,
              catalogue_variant_color_id: 11,
              catalogue_variant_color: {
                id: 11,
                name: "Limegreen",
                created_at: "2024-03-06T05:53:35.755Z",
                updated_at: "2024-05-07T12:27:33.725Z",
              },
              catalogue_variant_size_id: 1,
              catalogue_variant_size: {
                id: 1,
                name: "Small",
                created_at: "2023-09-22T04:45:35.966Z",
                updated_at: "2023-09-22T04:45:35.966Z",
              },
              price: "30.0",
              stock_qty: 7,
              on_sale: null,
              sale_price: null,
              discount_price: null,
              length: null,
              breadth: null,
              height: null,
              created_at: "2024-03-15T13:57:44.510Z",
              updated_at: "2024-05-15T07:32:29.114Z",
              sku: "hfgb",
              deactivate: false,
              low_stock_threshold: 0,
              is_listed: true,
              front_image:
                "https://sample.images/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWdGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4a527165bf8e36274a417f2274af13ec85a81394/profile.jpg",
              back_image: "",
              side_image: "",
              pair_it_with: [],
            },
          },
          {
            id: "310",
            type: "catalogue_variant",
            attributes: {
              id: 310,
              catalogue_id: 208,
              catalogue_variant_color_id: 10,
              catalogue_variant_color: {
                id: 10,
                name: "Whiteee",
                created_at: "2023-10-05T05:20:08.849Z",
                updated_at: "2023-10-05T05:20:08.849Z",
              },
              catalogue_variant_size_id: 1,
              catalogue_variant_size: {
                id: 1,
                name: "Small",
                created_at: "2023-09-22T04:45:35.966Z",
                updated_at: "2023-09-22T04:45:35.966Z",
              },
              price: "50.0",
              stock_qty: 7,
              on_sale: null,
              sale_price: null,
              discount_price: null,
              length: null,
              breadth: null,
              height: null,
              created_at: "2024-03-14T19:11:30.862Z",
              updated_at: "2024-04-18T19:53:58.552Z",
              sku: "Aa0o",
              deactivate: false,
              low_stock_threshold: 0,
              is_listed: true,
              front_image:
                "https://sample.images/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWNGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e18c009d1aa0936e582c33b6d9863b1b6dfd9787/profile.jpg",
              back_image: "",
              side_image: "",
              pair_it_with: [],
            },
          },
          {
            id: "309",
            type: "catalogue_variant",
            attributes: {
              id: 309,
              catalogue_id: 208,
              catalogue_variant_color_id: 7,
              catalogue_variant_color: {
                id: 7,
                name: "Grey",
                created_at: "2023-10-05T05:19:28.122Z",
                updated_at: "2023-10-05T05:19:28.122Z",
              },
              catalogue_variant_size_id: 1,
              catalogue_variant_size: {
                id: 1,
                name: "Small",
                created_at: "2023-09-22T04:45:35.966Z",
                updated_at: "2023-09-22T04:45:35.966Z",
              },
              price: "46.0",
              stock_qty: 0,
              on_sale: null,
              sale_price: null,
              discount_price: null,
              length: null,
              breadth: null,
              height: null,
              created_at: "2024-03-14T19:11:30.847Z",
              updated_at: "2024-04-18T09:37:39.170Z",
              sku: "sjsnsb",
              deactivate: false,
              low_stock_threshold: 0,
              is_listed: true,
              front_image:
                "https://sample.images/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVlGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cf4c16166068189ad8b443098e0486d755c627d5/profile.jpg",
              back_image: "",
              side_image: "",
              pair_it_with: [],
            },
          },
        ],
        primary_image:
          "https://sample.images/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVlGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cf4c16166068189ad8b443098e0486d755c627d5/profile.jpg",
        primary_price: "46.0",
        is_wishlist: false,
      },
    },
  ],
  meta: {
    total_pages: 16,
    current_page: 1,
    total_record: {
    },
    prev_page: null,
    next_page: 2,
  },
};

export const CarouselMockData = {
  data: [
    {
      id: "2",
      type: "landing_page_content",
      attributes: {
        id: 2,
        title: "TEST1",
        subtitle: "Demo1",
        description: "ckvvhkfdjg",
        link: "link",
        rank: 1,
        created_at: "2023-10-25T07:15:10.725Z",
        updated_at: "2023-10-25T07:20:52.635Z",
        image: "image.jpeg",
      },
    },
    {
      id: "3",
      type: "landing_page_content",
      attributes: {
        id: 3,
        title: "TEST1",
        subtitle: "DEMO1",
        description: "Test for test idsf  fjisdj ds ifjids fiiF pF IDJf sij uhv izdjisd",
        link: "lionk",
        rank: 2,
        created_at: "2023-10-25T07:18:20.408Z",
        updated_at: "2024-04-26T10:27:56.829Z",
        image: "image.jpeg",
      },
    },
  ],
};
