export const imgPasswordVisible = require("../assets/ic_password_visible.png");
export const imgPasswordInVisible = require("../assets/ic_password_invisible.png");
export const search = require("../assets/search.png");
export const backIcon = require("../assets/backIcon.png");
export const backIconWBG = require("../assets/backArrow.png");
export const backArrow1 = require("../assets/backArrow1.png");
export const filtern = require("../assets/filtern.png");
export const selectedCheckBox = require("../assets/selectedCheckBox.png");
export const unSelectedCheckBox = require("../assets/unselectCheckBox.png");
export const goBackIcon = require("../assets/goback.png");
export const errorIcon=require("../../catalogue/assets/errorIcon.jpg");
export const upload = require("../assets/export.png");
export const csvfile = require("../assets/csvfile.png");
export const arrorRight = require("../assets/arrow_right.png");
export const cancel = require("../assets/cross.png");
export const filter = require("../assets/filter.png");
export const downloadIcon = require("../assets/downlaodIcon.png");
export const rightArrow = require('../assets/arrowRight.png')
